Development
moka-guys/SNP_haplotyper pull request #2
Opened 2022-09-28 15:23 UTC by Graeme-Smith

Initial pull request of functioning AD and XL code

2022-10-07 13:51 UTC, aledj2 requested changes
> Reviewed 18 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 18 of 40 files reviewed, 17 unresolved discussions (waiting on @aledj2 and @Graeme-Smith)

___
*[`src/snp_haplotyper/excel_parser.py` line 7 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmZS4f9_s7inCP9qEg:-NDmZS4f9_s7inCP9qEh:b-aufwn1) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L7)):*
> ```Python
> import re
> 
> # Import command line arguments (these can be automatically generated from the sample sheet using sample_sheet_reader.py)
> ```

can it? that script needs to be updated



_Code quote:_
```Python
sample_sheet_reader.py
```
___
*[`src/snp_haplotyper/excel_parser.py` line 29 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmdX3I4Y39G0jDpL3Y:-NDmdX3I4Y39G0jDpL3Z:b-97sbok) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L29)):*
> ```Python
>     # Remove absolute symbols from string
>     range_string = range_string.replace("$", "")
>     if len(re.findall("[A-Z]+", range_string)) == 2:
> ```

so if the range extends over multiple columns
___
*[`src/snp_haplotyper/excel_parser.py` line 32 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmeKpe9eTK_szJjxjl:-NDmeKpe9eTK_szJjxjm:baj00sz) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L32)):*
> ```Python
>         col_start, col_end = re.findall("[A-Z]+", range_string)
>         data_rows = []
>         for row in ws[range_string]:
> ```

can we have a doc string explaining what `ws` contains and what `worksheet_and_range` contains. above you have extracted a range_string from worksheet_and_range and now you're getting one from ws
___
*[`src/snp_haplotyper/excel_parser.py` line 34 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmewAg3mhDXDrJr5yZ:-NDmewAg3mhDXDrJr5y_:b-5y0y9i) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L34)):*
> ```Python
>         for row in ws[range_string]:
>             data_rows.append([cell.value for cell in row])
>         range_contents = pd.DataFrame(
> ```

what does this df now hold?
___
*[`src/snp_haplotyper/excel_parser.py` line 40 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmf73_7TvI2oymM-vw:-NDmf73_7TvI2oymM-vx:bxwc845) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L40)):*
> ```Python
>         col_start = re.findall("[A-Z]+", range_string)
>         col_end = col_start
>         range_contents = ws[range_string].value
> ```

why capture col_start and col_end? not used?
___
*[`src/snp_haplotyper/excel_parser.py` line 56 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmZyA-6Huxh9HbG-cV:-NDmZyA-6Huxh9HbG-cW:buou3nv) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L56)):*
> ```Python
> # Get list of defined ranges from provided excel sheet
> defined_ranges = wb.defined_names
> print(defined_ranges)
> ```

assume this is a debug function to be commented? maybe a future release could produce a logfile to aid debugging?
___
*[`src/snp_haplotyper/excel_parser.py` line 59 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDm_Avx7XZLGx8n8Zt7:-NDm_Avx7XZLGx8n8Zt8:bwhq0t1) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L59)):*
> ```Python
> for dn in wb.defined_names.definedName:
>     print(dn.name)
>     print(dn.attr_text)
> ```

As above, do we still want print statements?



_Code quote:_
```Python
    print(dn.name)
    print(dn.attr_text)
```
___
*[`src/snp_haplotyper/excel_parser.py` line 60 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDm_KxZBA4J6M62UX2r:-NDm_KxZBA4J6M62UX2s:b-8wmmtb) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L60)):*
> ```Python
>     print(dn.name)
>     print(dn.attr_text)
>     if dn.attr_text is not None:
> ```

what is this test for?
___
*[`src/snp_haplotyper/excel_parser.py` line 61 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDm_pIn-L6L2sg9Yq0l:-NDm_pIoDxu1QPN3Fcub:b-9oj13r) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L61)):*
> ```Python
>     print(dn.attr_text)
>     if dn.attr_text is not None:
>         for worksheet_and_range in wb.defined_names[dn.name].destinations:
> ```

what format is data in .destinations ?



_Code quote:_
```Python
wb.defined_names[dn.name].destinations
```
___
*[`src/snp_haplotyper/excel_parser.py` line 62 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDm_RkrEmNGEL9ZaK-y:-NDm_RkrEmNGEL9ZaK-z:bb5c1a0) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L62)):*
> ```Python
>     if dn.attr_text is not None:
>         for worksheet_and_range in wb.defined_names[dn.name].destinations:
>             ws = wb.active
> ```

what does .active do?
___
*[`src/snp_haplotyper/excel_parser.py` line 136 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmgb8fEPBOK2nGZUkw:-NDmgb8fEPBOK2nGZUkx:b-zbebcx) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L136)):*
> ```Python
>     female_partner_status = partner1_type
>     female_partner_col = partner1_column_name
> ```

do we need an error catch here or is there data validation elsewhere?
___
*[`src/snp_haplotyper/excel_parser.py` line 137 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmgz-eAwSnEdRnp9Dg:-NDmgz-eAwSnEdRnp9Dh:b-fbkhne) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L137)):*
> ```Python
>     female_partner_col = partner1_column_name
> ```

what if any of the above are empty/not provided?
___
*[`src/snp_haplotyper/excel_parser.py` line 152 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmgoLB1nWxrbgr9d9E:-NDmgoLB1nWxrbgr9d9F:bowk9k4) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L152)):*
> ```Python
>         f" --female_partner {female_partner_col} --female_partner_status {female_partner_status}"
>         f" --reference {reference_col} --reference_status {reference_status}"
>         f" --reference_relationship {reference_relationship} --embryo_ids 24.F4.EMB11.rhchp 25.F4.EMB12.rhchp 26.F4.EMB13.rhchp"
> ```

guessing embryo_ids needs to be un-hardcoded . Also see embryo sex
___
*[`src/snp_haplotyper/excel_parser.py` line 156 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmhO2H14n66nmblh5r:-NDmhO2H14n66nmblh5s:b-xy158v) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L156)):*
> ```Python
>         f" --gene_end {gene_end} --chr {chromosome}")
>     )
> elif mode_of_inheritance == "Autosomal_Recessive":
> ```

the below looks no different to AD
___
*[`src/snp_haplotyper/excel_parser.py` line 170 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmhRV06QXERAYLc1Hj:-NDmhRV06QXERAYLc1Hk:b9qfr2g) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/e [...]

2022-10-19 20:49 UTC, aledj2 requested changes
> Reviewed 1 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 19 of 40 files reviewed, 26 unresolved discussions (waiting on @Graeme-Smith)

___
*[`src/snp_haplotyper/autosomal_dominant_logic.py` line 15 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NEaEWZ9EH72Biz-7kHz:-NEaEWZBAgfwvXN2Ksie:btfs7fa) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/autosomal_dominant_logic.py#L15)):*
> ```Python
>     reference_relationship,
> ):
>     """Identifies any SNPs which are "informative" and then categorises them as "high_risk" or "low_risk" for cases where the inheritance is autosomal dominant.
> ```

Note here a SNP is not a particular allele (eg A or B) but a site which could be used to inform a decision
___
*[`src/snp_haplotyper/autosomal_dominant_logic.py` line 40 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NEG_4kwAEZMfwOlN5rv:-NEG_4kwAEZMfwOlN5rw:b68y6xv) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/autosomal_dominant_logic.py#L40)):*
> ```Python
> 
>     if reference_relationship in [
>         "grandparent",  # TODO populate with all appropriate relationships
> ```

missing relationships?
___
*[`src/snp_haplotyper/json2excel.py` line 1 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmi23p0yDpwTHSsW-O:-NDmi23q5IzBvoI30Gz_:b-ua66vf) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/json2excel.py#L1)):*
> ```Python
> import argparse
> ```

is this file used? can't see if being called anywhere. Assume it's something to help run tests?
___
*[`src/snp_haplotyper/snp_haplotype.py` line 372 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NEBkVJ3BX0hOVG32MIG:-NEBkVJ3BX0hOVG32MIH:b6fxlyr) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L372)):*
> ```Python
>     nocall = df[df["call_type"] == "NoCall"]
>     if nocall.shape[0] > 0:
>         trimmed_nocall = nocall.iloc[:, 1:]  # Trim first column
> ```

why trim first column? Is that an index column?
___
*[`src/snp_haplotyper/snp_haplotype.py` line 374 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NEBkxgg-bHoqJAxl7sS:-NEBkxgg-bHoqJAxl7sT:b-jga5as) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L374)):*
> ```Python
>         trimmed_nocall = nocall.iloc[:, 1:]  # Trim first column
>         trimmed_df = df.iloc[:, 1:]  # Trim first column
>         nocall_percentage = trimmed_nocall / trimmed_df.sum(axis=0)
> ```

this is a dataframe? 
___
*[`src/snp_haplotyper/snp_haplotype.py` line 376 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NEBl2oR27YsRH1Q660_:-NEBl2oR27YsRH1Q660a:b-z1b320) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L376)):*
> ```Python
>         nocall_percentage = trimmed_nocall / trimmed_df.sum(axis=0)
>         # Add descriptive column
>         nocall_percentage.insert(0, "call_type", "NoCall")
> ```

Is this a header row?
___
*[`src/snp_haplotyper/snp_haplotype.py` line 377 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NEBl5zT70GcXheH8aBO:-NEBl5zT70GcXheH8aBP:b-vpfnwn) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L377)):*
> ```Python
>         # Add descriptive column
>         nocall_percentage.insert(0, "call_type", "NoCall")
>         return nocall_percentage
> ```

What does this look like?
___
*[`src/snp_haplotyper/snp_haplotype.py` line 486 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NEm-YZq4O1zf3JIZWxq:-NEm-YZq4O1zf3JIZWxr:b-fh6hyd) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L486)):*
> ```Python
> 
> 
> def snps_by_region(df, mode_of_inheritance):
> ```

pick up from here
___
*[`src/snp_haplotyper/snp_haplotype.py` line 923 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NEaGsuC6EmNxLiuJbwf:-NEaGsuC6EmNxLiuJbwg:b-8pzfui) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L923)):*
> ```Python
>             args.reference_relationship,
>         )
>     elif args.mode_of_inheritance == "autosomal_recessive":
> ```

need to come back to this


<!-- Sent from Reviewable.io -->

2022-10-26 20:45 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 19 of 40 files reviewed, 28 unresolved discussions (waiting on @Graeme-Smith)

___
*[`src/snp_haplotyper/snp_haplotype.py` line 591 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFKz99X4IhhBbydbmgx:-NFKz99X4IhhBbydbmgy:b-xr1lqr) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L591)):*
> ```Python
> def summarised_snps_by_region(df, mode_of_inheritance):
>     """
>     TODO - check what this function does compared to snps_by_region()
> ```

still todo? does look like some duplication
___
*[`src/snp_haplotyper/snp_haplotype.py` line 728 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFL1UoaAjAuIK2K2OPr:-NFL1Uob7m6wJbZ3BsTN:by7hxbp) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L728)):*
> ```Python
>         elif mode_of_inheritance == "autosomal_recessive":
>             conditions = [
>                 (df["snp_risk_category"] == "high_risk") & (df[embryo] == "AB"),
> ```

if embryo is het can it be high risk?
___
*[`src/snp_haplotyper/snp_haplotype.py` line 729 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFL1bmD0DWNcozlliLQ:-NFL1bmD0DWNcozlliLR:b-76r0f8) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L729)):*
> ```Python
>             conditions = [
>                 (df["snp_risk_category"] == "high_risk") & (df[embryo] == "AB"),
>                 (df["snp_risk_category"] == "high_risk") & ((df[embryo] == "AA") | (df[embryo] == "BB")) & consanguineous,
> ```

reread with fresh eyes


<!-- Sent from Reviewable.io -->

2022-10-28 16:34 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 19 of 40 files reviewed, 43 unresolved discussions (waiting on @Graeme-Smith)

___
*[`src/snp_haplotyper/snp_haplotype.py` line 397 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFTwaaA9b7hEmHJspB7:-NFTwaaA9b7hEmHJspB8:bgwmh5t) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L397)):*
> ```Python
> 
>     The definition of ADO (Allele dropout) is used when there is a suspected biological origin for the
>     mismatch in haplotypes, due to uniparental inheritance of the allele i.e Parents AA, AB and an embryo AA,
> ```

might be losing it at this stage but AA seems like it can be explained as both parents could contribute an A? maybe parents could be AA or BB and embryo AB (and it's not x-linked)
___
*[`src/snp_haplotyper/snp_haplotype.py` line 403 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFTx4O7Bkyy2nlnT090:-NFTx4O7Bkyy2nlnT091:b-e4bkhj) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L403)):*
> ```Python
> 
>     Args:
>         male_partner_haplotype (string): Either "AA", "BB", or "AB" (NoCalls will throw an exception))
> ```

I don't think "nocall" throws an exception based on the code? maybe an error is recorded if parents are No Call but seems to allow NoCall in the embryo?
___
*[`src/snp_haplotyper/snp_haplotype.py` line 474 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFTxZzI2j0ptQ4ch5pf:-NFTxZzI2j0ptQ4ch5pg:b-rfcney) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L474)):*
> ```Python
>             case ["AB", "AB"]:
>                 result = (
>                     "Error! Haplotypes most be AA, BB, or AB"
> ```

not sure this error message is informative? should it be parent haplotypes need to be AA,BB or AB (embryo no calls have been picked up earlier)? or is this where the nocall exception mentioned in the docstring?
___
*[`src/snp_haplotyper/snp_haplotype.py` line 726 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFTPcSE6bkLxqxuCs9i:-NFTPcSF9ejTTGIMnSvQ:b9otmnb) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L726)):*
> ```Python
>                 conditions, values, default="uninformative"
>             )
>         elif mode_of_inheritance == "autosomal_recessive":
> ```

skipping this for now
___
*[`src/snp_haplotyper/snp_haplotype.py` line 728 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFL1UoaAjAuIK2K2OPr:-NFTPOfp1pRrbqRF6qsG:b-tnpi3m) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L728)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

if embryo is het can it be high risk?
</blockquote></details>

(for AR)
___
*[`src/snp_haplotyper/snp_haplotype.py` line 773 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFTQG1f72_K7GE4ZxiI:-NFTQG1f72_K7GE4ZxiJ:bjrpc97) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L773)):*
> ```Python
>                     (df["male_AA_snp_risk_category"] != "uninformative")
>                     & (df["male_BB_snp_risk_category"] != "uninformative")
>                     & (df[embryo] == "NoCall"),
> ```

if male embryo is AB is it changed to no call (or excluded) elsewhere? would this be sorted by the default statement when these categories are applied below?
___
*[`src/snp_haplotyper/snp_haplotype.py` line 786 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFTS1JaBlOOhhQLbvtp:-NFTS1JaBlOOhhQLbvtq:b-8rtji4) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L786)):*
> ```Python
>                 )
>             elif embryo_sex_lookup[embryo] == "unknown":
>                 pass  # TODO raise exception
> ```

#TODO
___
*[`src/snp_haplotyper/snp_haplotype.py` line 788 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFTS2yZE2DHK58rzqtw:-NFTS2yZE2DHK58rzqtx:b-8rtji4) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L788)):*
> ```Python
>                 pass  # TODO raise exception
>             else:
>                 pass  # TODO raise exception
> ```

#TODO
___
*[`src/snp_haplotyper/snp_haplotype.py` line 799 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFU-s976z-o6jAummsZ:-NFU-s976z-o6jAumms_:biv4eui) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L799)):*
> ```Python
>             axis=1,
>         )
>         # Rename any uninformative calls from "call" to "uninformative" so they are consistent
> ```

any reason this can't be done above? I think this is where call is assigned? (Just an Q - no need to change anything other than add reasoning into comments , if relevant)
___
*[`src/snp_haplotyper/snp_haplotype.py` line 809 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFU9nd-1e5RuqcLfE5Y:-NFU9nd-1e5RuqcLfE5Z:b-8r8fek) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L809)):*
> ```Python
> def summarise_embryo_results(df, embryo_ids):
>     """
>     # TODO Docstring
> ```

#todo
___
*[`src/snp_haplotyper/snp_haplotype.py` line 813 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFU9vsSCwsLVPSvQU2C:-NFU9vsSCwsLVPSvQU2D:b-bi6abl) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L813)):*
> ```Python
>     summary_embryo_results = pd.DataFrame()
>     for embryo in embryo_ids:
>         new_column = df[f"{embryo}_risk_category"].value_counts()
> ```

what does this category contain? and value_counts?
___
*[`src/snp_haplotyper/snp_haplotype.py` line 818 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFUBZUGE-Qp4S6X092H:-NFUBZUGE-Qp4S6X092I:b-8rtji4) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L818)):*
> ```Python
>         summary_embryo_results.fillna("0").astype(int).reset_index()
>     )
>     # Ensure same ordering of table accross samples TODO check it doesn't break if index not present
> ```

#TODO
___
*[`src/snp_haplotyper/snp_haplotype.py` line 960 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFU5N7F1ulhXkcfyhye:-NFU5N7F1ulhXkcfyhyf:bndz257) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L960)):*
> ```Python
>     )
> 
>     # Summarise embryo results
> ```

Can we have a some more descriptive comments throughout this section
___
*[`src/snp_haplotyper/snp_haplotype.py` line 970 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFURQ3r3KaHY5lU1UH5:-NFURQ3s-V8E6xD2xzQq:b-u97qg6) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L970)):*
> ```Python
> 
>     # Produce report
>     results_table_1 = produce_html_table(
> ```

got to this point
___
*[`src/snp_haplotyper/snp_plot.py` line 60 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFU3xR09oyXljptL5Vl:-NFU3xR09oyXljptL5Vm:b-8rtji4) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2 [...]

2022-10-31 11:52 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 19 of 40 files reviewed, 61 unresolved discussions (waiting on @Graeme-Smith)

___
*[`src/snp_haplotyper/snp_haplotype.py` line 972 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhd04w65YRnlt8AHXx:-NFhd04w65YRnlt8AHXy:bkizl04) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L972)):*
> ```Python
>     results_table_1 = produce_html_table(
>         results_df,
>         "results_table_1",
> ```

is this informative?
___
*[`src/snp_haplotyper/snp_haplotype.py` line 995 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhd3U497u4eED8ytpV:-NFhd3U497u4eED8ytpW:b-8rtji4) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_haplotype.py#L995)):*
> ```Python
>     )
> 
>     # TODO remove flow control
> ```

#TODO
___
*[`src/snp_haplotyper/snp_plot.py` line 277 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhd9HmEJPdl6Y6a5fx:-NFhd9HmEJPdl6Y6a5fy:b-8rtji4) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_plot.py#L277)):*
> ```Python
>     mode_of_inheritance,
> ):
>     # TODO Add dataframe
> ```

#TODO
___
*[`src/snp_haplotyper/snp_plot.py` line 277 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhdB5D8Xvav_fRq5Ff:-NFhdB5D8Xvav_fRq5Fg:bk1pmei) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_plot.py#L277)):*
> ```Python
>     mode_of_inheritance,
> ):
>     # TODO Add dataframe
> ```

missing docstring
___
*[`src/snp_haplotyper/snp_plot.py` line 284 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhh9iO3FG_70g-f0Um:-NFhh9iO3FG_70g-f0Un:b-fr225s) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_plot.py#L284)):*
> ```Python
>     for embryo in embryo_ids:
> 
>         fig = px.scatter(
> ```

please can you comment this function so it'd be easy to maintain in future
___
*[`src/snp_haplotyper/snp_plot.py` line 298 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhdXvT-q2m4fZJtMI6:-NFhdXvT-q2m4fZJtMI7:b-aywn3z) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_plot.py#L298)):*
> ```Python
>             ),
>             facet_col="snp_inherited_from"
>             if mode_of_inheritance == "autosomal_recessive"
> ```

is this a list comprehension that is split across multiple lines or is part of y axis?



_Code quote:_
```Python
            facet_col="snp_inherited_from"
            if mode_of_inheritance == "autosomal_recessive"
            else None,
            facet_col_wrap=1 if mode_of_inheritance == "autosomal_recessive" else 0,
```
___
*[`src/snp_haplotyper/snp_plot.py` line 328 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhh4biE7yNLKB8-JUC:-NFhh4biE7yNLKB8-JUD:b-8rtji4) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_plot.py#L328)):*
> ```Python
>                     "uniformative",
>                 ],
>                 # TODO check this has no effect for AD and XL
> ```

#TODO
___
*[`src/snp_haplotyper/snp_plot.py` line 358 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhh_AP0bJmdQMqzwuq:-NFhh_AP0bJmdQMqzwur:b-aem0gk) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_plot.py#L358)):*
> ```Python
>         # Format facet plot labels
>         fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
>         fig.for_each_annotation(lambda a: a.update(xshift=-680))
> ```

add comment as to why
___
*[`src/snp_haplotyper/snp_plot.py` line 388 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhiC9n0atnLHStU6S8:-NFhiC9n0atnLHStU6S9:b-rte61e) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_plot.py#L388)):*
> ```Python
>         )
> 
>         def get_counts(summary_df, embryo, multi_category):
> ```

does the code from the parent function (plot_results) run above and continue below? Can we format/move these two function (get_counts and add_snp_counts_annotation) to aid readability? do they need to be within this function (or am I misreading)?
___
*[`src/snp_haplotyper/snp_plot.py` line 388 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhilok7tMsUWJfOw_Z:-NFhilol9WYa8St84rbv:bt68nnj) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_plot.py#L388)):*
> ```Python
>         )
> 
>         def get_counts(summary_df, embryo, multi_category):
> ```

docstring/comments
___
*[`src/snp_haplotyper/snp_plot.py` line 396 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhiiFH-VAt7A8vB2al:-NFhiiFIE9LniIInhVjl:b101mmx) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_plot.py#L396)):*
> ```Python
> 
>         def add_snp_count_annotation(
>             facet_row,
> ```

docstring and comments
___
*[`src/snp_haplotyper/snp_plot.py` line 412 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhj1SUD7DI_J8zSKOh:-NFhj1SUD7DI_J8zSKOi:b-ze4gck) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_plot.py#L412)):*
> ```Python
>                     name=annotation_name_high_risk,
>                     x=[
>                         gene_start - 1900000,
> ```

1900000?
___
*[`src/snp_haplotyper/snp_plot.py` line 460 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhisdW0o63qPWv4cy0:-NFhisdW0o63qPWv4cy1:b-m81g79) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_plot.py#L460)):*
> ```Python
>             or mode_of_inheritance == "autosomal_dominant"
>         ):
>             add_snp_count_annotation(
> ```

add comment
___
*[`src/snp_haplotyper/snp_plot.py` line 474 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhjX1U0nZaVey_jHKI:-NFhjX1U0nZaVey_jHKJ:bv193c9) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_plot.py#L474)):*
> ```Python
>             )
>         # A faceted 3 plot figure is created for AR so that male and female SNPs can be separated out.
>         elif mode_of_inheritance == "autosomal_recessive":
> ```

not reviewed
___
*[`src/snp_haplotyper/stream_output.py` line 4 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhjxxQ9Lcsj9PNrS2-:-NFhjxxQ9Lcsj9PNrS20:bbt6244) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/stream_output.py#L4)):*
> ```Python
> 
> 
> def get_snp_count(df, pattern, category_col, snp_count_col):
> ```

comment/docstring
___
*[`src/snp_haplotyper/stream_output.py` line 14 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhjvooA-JAcma9Iysb:-NFhjvooA-JAcma9Iysc:bbt6244) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/stream_output.py#L14)):*
> ```Python
> 
> 
> def get_total_snp_count(df, category_col, snp_count_col):
> ```

comment/docstring
___
*[`src/snp_haplotyper/stream_output.py` line 14 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhpfuI7uUAaZgEoc4k:-NFhpfuI7uUAaZgEoc4l:b-gbyert) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15 [...]

2022-10-31 11:58 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 19 of 40 files reviewed, 63 unresolved discussions (waiting on @Graeme-Smith)

___
*[`tests/functional/test_snp_filtering.py` line 1 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhtzfa5O_OSYNlX2O0:-NFhtzfb5XpJp6tXh94n:bv193c9) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/tests/functional/test_snp_filtering.py#L1)):*
> ```Python
> from argparse import Namespace
> ```

not reviewed
___
*[`tests/unit/test_functions.py` line 1 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhu3pO5ZJHKIfy4PZm:-NFhu3pO5ZJHKIfy4PZn:bv193c9) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/tests/unit/test_functions.py#L1)):*
> ```Python
> import pytest
> ```

not reviewed


<!-- Sent from Reviewable.io -->

2022-10-31 12:00 UTC, aledj2 requested changes
> Reviewed 1 of 36 files at r1, 4 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 24 of 40 files reviewed, 65 unresolved discussions (waiting on @Graeme-Smith)

___
*[`src/snp_haplotyper/autosomal_recessive_logic.py` line 19 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhuPLnDF110UvsGkK_:-NFhuPLnDF110UvsGkKa:b-jroge2) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/autosomal_recessive_logic.py#L19)):*
> ```Python
>     # Cosanguineous samples should always have an affected reference
>     if consanguineous and reference_status == "unaffected":
>         raise ArgumentInputError(
> ```

nothing happens in this function
___
*[`src/snp_haplotyper/exceptions.py` line 9 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhuAH84ckGLLyv6Wig:-NFhuAH84ckGLLyv6Wih:bjlyifq) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/exceptions.py#L9)):*
> ```Python
> 
> class ArgumentInputError(Error):
>     """Raised when the input parameters do not make sense considering the underlying biology"""
> ```

need anything here?


<!-- Sent from Reviewable.io -->

2022-12-09 15:13 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 24 of 40 files reviewed, 65 unresolved discussions (waiting on @aledj2)

___
*[`src/snp_haplotyper/autosomal_dominant_logic.py` line 15 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NEaEWZ9EH72Biz-7kHz:-NGMcQ5n6gQ7GMclX97r:bj9rfdb) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/autosomal_dominant_logic.py#L15)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Note here a SNP is not a particular allele (eg A or B) but a site which could be used to inform a decision
</blockquote></details>

Changed it to - Identifies any SNP site which could be used to inform a decision regarding inheriting an autosomal dominant condition ("informative" SNPs) and categorizes the site as  indicating "high_risk" or "low_risk" of inheriting an autosomal dominant condition if that site is heterozygous (AB) in the embryo.
"
___
*[`src/snp_haplotyper/autosomal_dominant_logic.py` line 40 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NEG_4kwAEZMfwOlN5rv:-NGMdyVo0FB30d8K2Vru:b-s9hexb) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/autosomal_dominant_logic.py#L40)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

missing relationships?
</blockquote></details>

Removed this comment as this if condition only applies to grandparent refs - child, embryo are dealt with in a separate if clause
___
*[`src/snp_haplotyper/autosomal_recessive_logic.py` line 19 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhuPLnDF110UvsGkK_:-NG0wlpR1KBuOHeHhQZr:bcxvqhh) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/autosomal_recessive_logic.py#L19)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

nothing happens in this function
</blockquote></details>

All consanguineous references will be affected - this condition is  to catch any illogical data input (consanguienous==True, Unaffected==True) and return an error message and halt the analysis. Note consanguineous is a separate flag to reference_status
___
*[`src/snp_haplotyper/excel_parser.py` line 7 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmZS4f9_s7inCP9qEg:-NIqvJig5wVRLPjHIfff:b-wfkbr7) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L7)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can it? that script needs to be updated
</blockquote></details>

Script has been updated
___
*[`src/snp_haplotyper/excel_parser.py` line 29 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmdX3I4Y39G0jDpL3Y:-NIr7HcQ4MzyuyA9n8_g:b-e2467s) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L29)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

so if the range extends over multiple columns
</blockquote></details>

Code has been refactored - ranges are now imported using custom code for each of the two ranges
___
*[`src/snp_haplotyper/excel_parser.py` line 32 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmeKpe9eTK_szJjxjl:-NIrBXk8046Y6ZeERdK7:bzajvcq) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L32)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can we have a doc string explaining what `ws` contains and what `worksheet_and_range` contains. above you have extracted a range_string from worksheet_and_range and now you're getting one from ws
</blockquote></details>

Added doc string code refactored to make it easier to read.
___
*[`src/snp_haplotyper/excel_parser.py` line 34 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmewAg3mhDXDrJr5yZ:-NIrBeNS5Xo-ADlpnXRq:bsl9e6h) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L34)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what does this df now hold?
</blockquote></details>

Refactored so more human readable - holds either partner1, partner2, or embryo details depending on what is entered into function (see docstrings to see columns)
___
*[`src/snp_haplotyper/excel_parser.py` line 40 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmf73_7TvI2oymM-vw:-NIrBzur6aTqejqWuWsU:b460ekg) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L40)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

why capture col_start and col_end? not used?
</blockquote></details>

Now used to prevent empty cells being imported
___
*[`src/snp_haplotyper/excel_parser.py` line 56 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmZyA-6Huxh9HbG-cV:-NIrCHxs4i07PEyQFRN-:bjlacnv) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L56)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

assume this is a debug function to be commented? maybe a future release could produce a logfile to aid debugging?
</blockquote></details>

Will add to logger when supported



_Code quote:_
```Python
defined_ranges = wb.defined_names
```
___
*[`src/snp_haplotyper/excel_parser.py` line 59 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDm_Avx7XZLGx8n8Zt7:-NIrFR_3Ax0wFd-7bVHf:b-g8kuou) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L59)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

As above, do we still want print statements?
</blockquote></details>

Refactored - will add to logging when implemented
___
*[`src/snp_haplotyper/excel_parser.py` line 60 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDm_KxZBA4J6M62UX2r:-NIrC_QDCgd74eaBL1ha:b-wm6qwb) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L60)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what is this test for?
</blockquote></details>

Nothing - removed



_Code quote:_
```Python
if dn.attr_text is not None:
```
___
*[`src/snp_haplotyper/excel_parser.py` line 61 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDm_pIn-L6L2sg9Yq0l:-NIrCidM8eYdr7eiN2dX:b9w7fma) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L61)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what format is data in .destinations ?
</blockquote></details>

Code removed



_Code quote:_
```Python
 for worksheet_and_range in wb.defined_names[dn.name].destinations:
```
___
*[`src/snp_haplotyper/excel_parser.py` line 62 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDm_RkrEmNGEL9ZaK-y:-NIrCquP3DnOmGdADT3N:bc79je7) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/excel_parser.py#L62)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what does .active do?
</blockquote></details>

Code removed - now specify the name of the worksheet explicitly



_Code quote [...]

2022-12-11 12:17 UTC, aledj2 requested changes
> Reviewed 1 of 53 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 10 of 64 files reviewed, 72 unresolved discussions (waiting on @Graeme-Smith)

___
*[`snp_haplotyper/config.py` line 15 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ0-d1T0oHdZrA6U5NA:-NJ0-d1T0oHdZrA6U5NB:b-lciu70) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/config.py#L15)):*
> ```Python
> # to skip the analysis of other modes of inheritance
> allow_autosomal_dominant_cases = True
> allow_autosomal_recessive_cases = True
> ```

need to change these to False as appropriate for v1.0
___
*[`snp_haplotyper/snp_haplotype.py` line 14 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-p2S00BXjHjIosixp:-NJ-p2S00BXjHjIosixq:by82x08) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L14)):*
> ```Python
> from autosomal_dominant_logic import autosomal_dominant_analysis
> from autosomal_recessive_logic import autosomal_recessive_analysis
> from config import (
> ```

More of an FYI/issue to be raised for a later version but when importing from config in other scripts I use `import config as config` then in the code you can access with `config.genome_build` which makes it clear that variable is coming from the config file. also means don't need to specify which variants to import here
___
*[`snp_haplotyper/snp_haplotype.py` line 220 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-osMTB79AlHT7hFMQ:-NJ-osMTB79AlHT7hFMR:byyckkv) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L220)):*
> ```Python
> 
> parser.add_argument(
>     "--trio_only",
> ```

I assume this is ready for release in v1.0 ? (wondering if it could be added to config)
___
*[`snp_haplotyper/snp_haplotype.py` line 830 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-wkP8D80TgwOJ1DLu:-NJ-wkP8D80TgwOJ1DLv:b-cytedp) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L830)):*
> ```Python
>                 conditions, values, default="uninformative"
>             )
>         elif mode_of_inheritance == "autosomal_recessive":
> ```

not reviewed - need to revisit
___
*[`snp_haplotyper/snp_haplotype.py` line 835 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-wWKh7HynOog3opUI:-NJ-wWKh7HynOog3opUJ:bxyhc2x) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L835)):*
> ```Python
>                 (df["snp_risk_category"] == "high_risk")
>                 & (df["snp_inherited_from"] == "male_partner")
>                 & (df[embryo] == "AB"),
> ```

high risk heterozygous call?
___
*[`snp_haplotyper/snp_haplotype.py` line 989 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-y4Mb83sIihkjCgMs:-NJ-y4Mb83sIihkjCgMt:b9h4v8) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L989)):*
> ```Python
>     embryo_ids,
>     mode_of_inheritance,
> ):
> ```

docstring
___
*[`snp_haplotyper/snp_haplotype.py` line 990 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-yJxV9h3ekUNSjDPv:-NJ-yJxV9h3ekUNSjDPw:byugwvi) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L990)):*
> ```Python
>     mode_of_inheritance,
> ):
>     counter = 0
> ```

just fyi could use enuemrate() - allows you to access the item in a list, and the index of that item, I think this removes the need for counter
___
*[`snp_haplotyper/snp_haplotype.py` line 1002 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-yul-6jm5ZfONV9NQ:-NJ-yul-6jm5ZfONV9NR:b-6lc8th) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L1002)):*
> ```Python
>         elif counter > 0:
>             temp_df = (
>                 df.groupby(["gene_distance", f"{embryo}_risk_category"])
> ```

sorry, I don't follow this - could you comment please?
___
*[`snp_haplotyper/snp_haplotype.py` line 1096 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ0024gB8QVCVCb5j6j:-NJ0024gB8QVCVCb5j6k:b-8zvw5s) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L1096)):*
> ```Python
>     ):
>         raise InvalidParameterSelectedError(
>             "Please check the config.py file to see whether autosomal dominant samples are supported in the current release"
> ```

if this is displayed to user I'd phrase it as This mode on inheritance is not supported by this release
___
*[`snp_haplotyper/snp_haplotype.py` line 1103 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ0-u0ZAeD-HzrIVDOX:-NJ0-u0ZAeD-HzrIVDOY:b-8zvw5s) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L1103)):*
> ```Python
>     ):
>         raise InvalidParameterSelectedError(
>             "Please check the config.py file to see whether autosomal recessive samples are supported in the current release"
> ```

if this is displayed to user I'd phrase it as This mode on inheritance is not supported by this release
___
*[`snp_haplotyper/snp_haplotype.py` line 1107 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ004qR1hCFDgbw_4G_:-NJ004qR1hCFDgbw_4Ga:b-8zvw5s) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L1107)):*
> ```Python
>     elif allow_x_linked_cases == False and args.mode_of_inheritance == "x_linked":
>         raise InvalidParameterSelectedError(
>             "Please check the config.py file to see whether x-linked samples are supported in the current release"
> ```

if this is displayed to user I'd phrase it as This mode on inheritance is not supported by this release
___
*[`snp_haplotyper/snp_haplotype.py` line 1112 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ003_wEcTf8gsYzuWo:-NJ003_wEcTf8gsYzuWp:b-8zvw5s) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L1112)):*
> ```Python
>     elif allow_cosanguineous_cases == False and args.consanguieous == True:
>         raise InvalidParameterSelectedError(
>             "Please check the config.py file to see whether consanguineous samples are supported in the current release"
> ```

if this is displayed to user I'd phrase it as This mode on inheritance is not supported by this release
___
*[`snp_haplotyper/snp_haplotype.py` line 1209 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ00J4C5VqqLs4i3dmY:-NJ00J4C5VqqLs4i3dmZ:b3ac07s) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L1209)):*
> ```Python
>     informative_snps_by_region = snps_by_region(results_df, args.mode_of_inheritance)
> 
>     print(informative_snps_by_region)
> ```

Should this print statement (and the one below) be in an if loop to do with streaming output?
___
*[`snp_haplotyper/snp_haplotype.py` line 1239 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ00gHi80T2tm9ILXod:-NJ00gHj5ez2xUCfF29S:b35ynzi) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L1239)):*
> ```Python
>     # summary_embryo_df = summarise_embryo_results(embryo_category_df, args.embryo_ids)
> 
>     ################################# [...]

2022-12-12 17:48 UTC, aledj2 requested changes
> Reviewed 2 of 53 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 12 of 64 files reviewed, 72 unresolved discussions (waiting on @Graeme-Smith)

___
*[`snp_haplotyper/excel_parser.py` line 105 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ5yZVp7DgjqWrGfWQX:-NJ5yZVp7DgjqWrGfWQY:bopy5l9) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/excel_parser.py#L105)):*
> ```Python
>     data_entry_sheet = wb["data_entry"]
> 
>     for dn in wb.defined_names.definedName:
> ```

not sure it matters but an object for wb.defined_names was created above so this could/should be defined_ranges? although defined_ranges is not used so maybe that could be deleted instead?



_Code quote:_
```Python
wb.defined_names
```
___
*[`snp_haplotyper/excel_parser.py` line 113 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ5zKZ44anMnd3QyONJ:-NJ5zKZ44anMnd3QyONK:basg4ih) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/excel_parser.py#L113)):*
> ```Python
>             # Import excel ranges
>             df = load_workbook_range(
>                 dn.attr_text.split("!")[1].replace("$", ""), data_entry_sheet
> ```

why are these treated differently to the other inputs?
___
*[`snp_haplotyper/excel_parser.py` line 210 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ6-lndCdG8Y5dAb5uS:-NJ6-lndCdG8Y5dAb5uT:bpz1kdo) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/excel_parser.py#L210)):*
> ```Python
>         f" --female_partner {female_partner_col} --female_partner_status {female_partner_status}"
>         f" --reference {reference} --reference_status {ref_status}"
>         f" --reference_relationship {ref_relationship} --embryo_ids 24.F4.EMB11.rhchp 25.F4.EMB12.rhchp 26.F4.EMB13.rhchp"
> ```

hardcoded embryo information?
___
*[`snp_haplotyper/excel_parser.py` line 221 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ600wMAR3_xxmR0MF5:-NJ600wMAR3_xxmR0MF6:b29nvj8) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/excel_parser.py#L221)):*
> ```Python
>     if mode_of_inheritance == "Autosomal_Dominant":
>         pass
>     elif mode_of_inheritance == "Autosomal_Recessive":
> ```

needs to be updated?



_Code quote:_
```Python
    print(mode_of_inheritance)
    if mode_of_inheritance == "Autosomal_Dominant":
        pass
    elif mode_of_inheritance == "Autosomal_Recessive":
        pass
    elif mode_of_inheritance == "x_linked":
        pass
    else:
        pass  # raise exception
```
___
*[`snp_haplotyper/autosomal_recessive_logic.py` line 15 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ5oAb-DKBcFGb6vGAk:-NJ5oAb-DKBcFGb6vGAl:b-r06h2h) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/autosomal_recessive_logic.py#L15)):*
> ```Python
> ):
>     """Identifies any SNP site which could be used to inform a decision regarding inheriting an autosomal recessive condition ("informative" SNPs) and categorizes
>     the site as  indicating "high_risk" or "low_risk" of inheriting an autosomal recessive condition if that site is heterozygous (AB) in the embryo.  For consanguineous
> ```

surely for AR needs to be homozygous?



_Code quote:_
```Python
heterozygous (AB)
```
___
*[`snp_haplotyper/autosomal_recessive_logic.py` line 21 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ6RBi38GmqR3AZYasl:-NJ6RBi38GmqR3AZYasm:b-mxb578) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/autosomal_recessive_logic.py#L21)):*
> ```Python
>     This function asks the question - For the combination of haplotypes present in the reference trio (reference,
>     unaffected_partner and affected_partner) what information would this SNP provide us with if the SNP was
>     AB in the embryo - does the SNP indicate "high_risk", "low_risk", or is it "uninformative"? Additioanlly for
> ```

I don't think this is correct for AR. But for when I pick this code review up again - A probe is determined high risk or not depending if it is shared or different to the reference,(considering the affected status of the reference) - then the probe is classified as being inherited from male or female partner.

Therefore when plotting for each embryo need to check how a embryo is seen as having the site or not.



_Code quote:_
```Python
AB in 
```
___
*[`snp_haplotyper/snp_plot.py` line 438 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ5tpsX3Us3RMLffQSn:-NJ5tpsX3Us3RMLffQSo:b-agx3bl) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_plot.py#L438)):*
> ```Python
> 
>         # Functions to add SNP count annotations to plot
>         # TODO will refactor to reduce code duplication as calculated in main script
> ```

will this be added as an issue?
___
*[`snp_haplotyper/snp_plot.py` line 530 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ5v7XvEnDUgY9g30Dm:-NJ5v7XvEnDUgY9g30Dn:bz0yo4y) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_plot.py#L530)):*
> ```Python
>         # A faceted 3 plot figure is created for AR so that male and female SNPs can be separated out.
>         elif mode_of_inheritance == "autosomal_recessive":
>             add_snp_count_annotation(
> ```

comment # add male plot
___
*[`snp_haplotyper/snp_plot.py` line 544 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ5vCCNAp107qa1bgVy:-NJ5vCCNAp107qa1bgVz:b-cfcljx) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_plot.py#L544)):*
> ```Python
>             )
> 
>             add_snp_count_annotation(
> ```

comment # add female plot (reason for this and above is confusion over what variable is passed) 
And also, that strings, or variable names are passed
___
*[`src/snp_haplotyper/json2excel.py` line 1 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmi23p0yDpwTHSsW-O:-NJ60JNu0OfotGSdudjr:bp76350) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/json2excel.py#L1)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Not currently used - in future might be used to populate excel spreadsheet templates with the test data which is currently in JSON format - this could then be used to test the excel_parser.py script but Heema/Pam have supplied manually filled spreadsheets which could also be used.
</blockquote></details>

in which case can it be moved/separated so it's clear it hasn't been code reviewed or that it's in use?
___
*[`src/snp_haplotyper/sample_sheet_reader.py` line 1 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NDmZDkN3ESBO2FlndS3:-NJ60k322xWjSFUzqpyu:b4kaef3) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/sample_sheet_reader.py#L1)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

It's now been updated
</blockquote></details>

don't think that's made it's way into the version control
___
*[`src/snp_haplotyper/snp_plot.py` line 358 at r2](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NFhh_AP0bJmdQMqzwuq:-NJ5tZNs07HTrn3o9Mvs:bxthh88) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/5dfb15c44a9b53501112e2a883ec9c2219dbb33b/src/snp_haplotyper/snp_plot.py#L358)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>
 [...]

2022-12-13 00:45 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 12 of 64 files reviewed, 72 unresolved discussions (waiting on @aledj2)

___
*[`snp_haplotyper/config.py` line 15 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ0-d1T0oHdZrA6U5NA:-NJ7LoTG-Nd7AmrTIi3E:b-896fjb) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/config.py#L15)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

need to change these to False as appropriate for v1.0
</blockquote></details>

Done 
___
*[`snp_haplotyper/excel_parser.py` line 105 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ5yZVp7DgjqWrGfWQX:-NJ7Lz3TBjbMQ2bYCKV6:b-q18qf4) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/excel_parser.py#L105)):*
> wb.defined_names
Added a Todo - I left this code in because I will write this out to the log file when logger is added 
___
*[`snp_haplotyper/excel_parser.py` line 113 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ5zKZ44anMnd3QyONJ:-NJ7Nvlt-kvA74xm8dKg:b2n6t7b) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/excel_parser.py#L113)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

why are these treated differently to the other inputs?
</blockquote></details>

The other defined ranges are single cells - partner details are a range of          partner1_type,partner1_sex,partner1_forename,partner1_surname,partner1_dob,partner1_DNA_number,partner1_column_name,

embrto_data is a range of         "biopsy_no",  "embryo_id",  "embryo_sex". "embryo_column_name", with the added complication that it could be 0 or n rows depending on the number of embryos
___
*[`snp_haplotyper/excel_parser.py` line 210 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ6-lndCdG8Y5dAb5uS:-NJ7O_e2EQ3f7YPyvp8A:b-5za06n) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/excel_parser.py#L210)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

hardcoded embryo information?
</blockquote></details>

This has been updated - I will push the latest changes
___
*[`snp_haplotyper/excel_parser.py` line 221 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ600wMAR3_xxmR0MF5:-NJ7OiEEELTQ_Rng9M-s:bb6un1j) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/excel_parser.py#L221)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

needs to be updated?
</blockquote></details>

Done
___
*[`snp_haplotyper/autosomal_recessive_logic.py` line 15 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ5oAb-DKBcFGb6vGAk:-NJ7qmlI62Ap3MLOSnD_:b-m8kczs) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/autosomal_recessive_logic.py#L15)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

surely for AR needs to be homozygous?
</blockquote></details>

I believe our discussion cleared this up?
___
*[`snp_haplotyper/autosomal_recessive_logic.py` line 21 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ6RBi38GmqR3AZYasl:-NJ7usm02XbM1fC4v1RX:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/autosomal_recessive_logic.py#L21)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I don't think this is correct for AR. But for when I pick this code review up again - A probe is determined high risk or not depending if it is shared or different to the reference,(considering the affected status of the reference) - then the probe is classified as being inherited from male or female partner.

Therefore when plotting for each embryo need to check how a embryo is seen as having the site or not.
</blockquote></details>

Done.
___
*[`snp_haplotyper/snp_haplotype.py` line 14 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-p2S00BXjHjIosixp:-NJ7PKLE9LcqtClFiUlY:b-so9fo5) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L14)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

More of an FYI/issue to be raised for a later version but when importing from config in other scripts I use `import config as config` then in the code you can access with `config.genome_build` which makes it clear that variable is coming from the config file. also means don't need to specify which variants to import here
</blockquote></details>

Changed to the above style
___
*[`snp_haplotyper/snp_haplotype.py` line 220 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-osMTB79AlHT7hFMQ:-NJ7PQeP2ce_LQNg_yYJ:b-c4iyz1) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L220)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I assume this is ready for release in v1.0 ? (wondering if it could be added to config)
</blockquote></details>

Argument included but code disabled - if trio_only flag used will throw an exception saying not supported as per config file
___
*[`snp_haplotyper/snp_haplotype.py` line 830 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-wkP8D80TgwOJ1DLu:-NJ7TzbbDOqi9AhVdHS0:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L830)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

not reviewed - need to revisit
</blockquote></details>

Done.
___
*[`snp_haplotyper/snp_haplotype.py` line 835 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-wWKh7HynOog3opUI:-NJ7rqyy5FMtKHXEQS6X:bwbf398) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L835)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

high risk heterozygous call?
</blockquote></details>

Hopefully our call cleared this up.
___
*[`snp_haplotyper/snp_haplotype.py` line 989 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-y4Mb83sIihkjCgMs:-NJ7cHL37nesTe4NM9sJ:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L989)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.



_Code quote:_
```Python
    return df
```
___
*[`snp_haplotyper/snp_haplotype.py` line 990 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-yJxV9h3ekUNSjDPv:-NJ7haFB0qHtECiZfDfk:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L990)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

just fyi could use enuemrate() - allows you to access the item in a list, and the index of that item, I think this removes the need for counter
</blockquote></details>

Done.
___
*[`snp_haplotyper/snp_haplotype.py` line 1002 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-yul-6jm5ZfONV9NQ:-NJ7hger7QY43HoKXkl_:b861h7g) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L1002)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wro [...]

2022-12-13 09:53 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 10 of 65 files reviewed, 72 unresolved discussions (waiting on @aledj2)

___
*[`snp_haplotyper/snp_haplotype.py` line 1292 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ01z2G9el0mm5656Eb:-NJ9tHDX27uNbY9bkq9r:bk2p8an) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L1292)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

i can't follow what temp_df contains after groupby
</blockquote></details>

It adds a new column which groups the rows by upstream, downstream, and within_gene - currently not used and will be refactored out in future release.


<!-- Sent from Reviewable.io -->

2022-12-13 13:30 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 10 of 65 files reviewed, 57 unresolved discussions (waiting on @Graeme-Smith)

___
*[`snp_haplotyper/autosomal_recessive_logic.py` line 15 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ5oAb-DKBcFGb6vGAk:-NJAJd88Ex3zwiiihfnF:bh5opi5) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/autosomal_recessive_logic.py#L15)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

I believe our discussion cleared this up?
</blockquote></details>

yes, I think the status of the embryo is irrelevant in this function, however this function is classifying sites in a way that we can use AB calls in the embryo.

Perhaps could rephrase docstring as:

    """Identifies any "informative" probes because, if the embryo was heterozygous, we could identify who an allele was inherited from and if it is shared by the affected/unaffected reference. For example, if the male partner is AA and female partner AB and the B allele is also in the affected reference we could say that if the embryo was AB it must have inherited a high risk allele from the female partner.  

To be fair the docstring does go on to say the same as I've just written! I don't think it makes it clear that it defines it as high risk and which partner it is inherited from - as these are both displayed in the end report and this is used to define if the embryo has inherited high risk alleles from 0, 1 or 2 parents - as this will determine the end status of the embryo
___
*[`snp_haplotyper/autosomal_recessive_logic.py` line 16 at r4](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJAeNMX-Y0wRj22hD0m:-NJAeNMX-Y0wRj22hD0n:b-53noiy) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/1057b504422303250ea205e8a94a74d2b66dd268/snp_haplotyper/autosomal_recessive_logic.py#L16)):*
> ```Python
>     """Identifies any SNP site which could be used to inform a decision regarding inheriting an autosomal recessive condition ("informative" SNPs) and categorizes
>     the site as  indicating "high_risk" or "low_risk" of inheriting an autosomal recessive condition if that site is heterozygous (AB) in the embryo.  For consanguineous
>     cases (where "informative" SNPs can be limited) the function also considers sites TODO
> ```

can you make the consanguinous description in the doc string clear that it is TODO? Maybe a new line?



_Suggestion:_
```Python
For consanguineous cases (where "informative" SNPs can be limited) the function also considers sites TODO
```
___
*[`snp_haplotyper/autosomal_recessive_logic.py` line 18 at r4](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJAJW4h7ZSQj2CWDSSy:-NJAJW4h7ZSQj2CWDSSz:b-7isi7g) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/1057b504422303250ea205e8a94a74d2b66dd268/snp_haplotyper/autosomal_recessive_logic.py#L18)):*
> ```Python
>     cases (where "informative" SNPs can be limited) the function also considers sites TODO
>     # TODO change google doc link to link to read the docs.
>     The full logic behind the function is described here TODO
> ```

todo?



_Code quote:_
```Python
e TODO
```
___
*[`snp_haplotyper/snp_haplotype.py` line 835 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-wWKh7HynOog3opUI:-NJAObBD6iyouutU0m_c:b-m8eoh3) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L835)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Hopefully our call cleared this up.
</blockquote></details>

yes - see docstring suggestion
___
*[`snp_haplotyper/snp_haplotype.py` line 1002 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-yul-6jm5ZfONV9NQ:-NJAbbgA1Idil0ExcK_3:brhw4z) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L1002)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Its acting like a pivot table producing a breakdown of the number in each category of gene_distance and risk category - .size() tells the function to count the number of occurrences rather than say .sum() and .reset_index() converts it from a groupby object with two indexes - gene_distance and risk_category  into one index of gene_distance, risk_category,  See below for the gropby object
 
![image.png](https://files.reviewableusercontent.io/images/reviewable/7481968/PiJLmI3f7epd8G2_9oWukghf/image.png)

</blockquote></details>

makes sense, can this be added as comment please?
___
*[`snp_haplotyper/snp_haplotype.py` line 790 at r4](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJAZgsf44PWEw_hQeyd:-NJAZgsf44PWEw_hQeye:bff0cev) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/1057b504422303250ea205e8a94a74d2b66dd268/snp_haplotyper/snp_haplotype.py#L790)):*
> ```Python
>     consanguineous,
> ):
>     """For each embryo this fuction categorises their SNPs
> ```

Note the usable/informative genotypes for each mode of inheritance are hardcoded into this function. these have been defined with the PGD team. Note genotypes are defined as usable based on whether we can trace the inheritance from a parent AND if it's shared by an affected/unaffected reference and NOT if it matches with the required genotype to perform a SNV analysis of that site, eg In AR condition, if performing SNV analysis would be interested in homozygous sites but these sites are not informative in this application - only heterozygous sites allow us to determine who an allele was inherited from and if it's shared by the reference.


<!-- Sent from Reviewable.io -->

2022-12-13 15:03 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 10 of 65 files reviewed, 58 unresolved discussions (waiting on @aledj2)

___
*[`snp_haplotyper/autosomal_recessive_logic.py` line 15 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ5oAb-DKBcFGb6vGAk:-NJAzq_wASrGHg5qsduz:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/autosomal_recessive_logic.py#L15)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

yes, I think the status of the embryo is irrelevant in this function, however this function is classifying sites in a way that we can use AB calls in the embryo.

Perhaps could rephrase docstring as:

    """Identifies any "informative" probes because, if the embryo was heterozygous, we could identify who an allele was inherited from and if it is shared by the affected/unaffected reference. For example, if the male partner is AA and female partner AB and the B allele is also in the affected reference we could say that if the embryo was AB it must have inherited a high risk allele from the female partner.  

To be fair the docstring does go on to say the same as I've just written! I don't think it makes it clear that it defines it as high risk and which partner it is inherited from - as these are both displayed in the end report and this is used to define if the embryo has inherited high risk alleles from 0, 1 or 2 parents - as this will determine the end status of the embryo
</blockquote></details>

Done.
___
*[`snp_haplotyper/autosomal_recessive_logic.py` line 16 at r4](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJAeNMX-Y0wRj22hD0m:-NJB-Kkp7jWhR05fRr_9:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/1057b504422303250ea205e8a94a74d2b66dd268/snp_haplotyper/autosomal_recessive_logic.py#L16)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can you make the consanguinous description in the doc string clear that it is TODO? Maybe a new line?
</blockquote></details>

Done.
___
*[`snp_haplotyper/autosomal_recessive_logic.py` line 18 at r4](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJAJW4h7ZSQj2CWDSSy:-NJB-M5G35z6zhC17h0U:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/1057b504422303250ea205e8a94a74d2b66dd268/snp_haplotyper/autosomal_recessive_logic.py#L18)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

todo?
</blockquote></details>

Done.
___
*[`snp_haplotyper/snp_haplotype.py` line 1002 at r3](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJ-yul-6jm5ZfONV9NQ:-NJAyuEAA-NymWInC_hx:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/7b43b6fe29efaf1efa642f64abcf15e5b985e19a/snp_haplotyper/snp_haplotype.py#L1002)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

makes sense, can this be added as comment please?
</blockquote></details>

Done.
___
*[`snp_haplotyper/snp_haplotype.py` line 790 at r4](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJAZgsf44PWEw_hQeyd:-NJB-aom2ngoIxw_EX6a:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/1057b504422303250ea205e8a94a74d2b66dd268/snp_haplotyper/snp_haplotype.py#L790)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Note the usable/informative genotypes for each mode of inheritance are hardcoded into this function. these have been defined with the PGD team. Note genotypes are defined as usable based on whether we can trace the inheritance from a parent AND if it's shared by an affected/unaffected reference and NOT if it matches with the required genotype to perform a SNV analysis of that site, eg In AR condition, if performing SNV analysis would be interested in homozygous sites but these sites are not informative in this application - only heterozygous sites allow us to determine who an allele was inherited from and if it's shared by the reference.
</blockquote></details>

Done.
___
*[`snp_haplotyper/snp_haplotype.py` line 1033 at r4](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJAysWb8ggLbEfGA502:-NJAysWb8ggLbEfGA503:bbbo5bc) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/1057b504422303250ea205e8a94a74d2b66dd268/snp_haplotyper/snp_haplotype.py#L1033)):*
> pivot table producing a breakdown of the number in each category of gene_distance and risk category - .size() tells the function to count the number of occurrences rather than say .sum() and .reset_index() converts it from a groupby object with two indexes - gene_distance and risk_category  into one index of gene_distance, risk_category,  See below for the gropby object


<!-- Sent from Reviewable.io -->

2022-12-13 16:15 UTC, aledj2 reviewed
> Reviewed 2 of 16 files at r4, 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 14 of 65 files reviewed, 28 unresolved discussions (waiting on @Graeme-Smith)



<!-- Sent from Reviewable.io -->

2022-12-13 16:59 UTC, aledj2 reviewed
> Reviewed 1 of 53 files at r3, 1 of 16 files at r4, 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 17 of 65 files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

___
*[`tests/functional/test_snp_filtering.py` line 179 at r5](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJBMQpb6oF8e3Q93X9Z:-NJBMQpb6oF8e3Q93X9_:b-mqb70t) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/75b69e44ffc1455e8b00188cc7de7201979bd9bf/tests/functional/test_snp_filtering.py#L179)):*
> ```Python
>         assert (
>             results["low_risk_snps_downstream_2mb"]
>             == validation["low_risk_snps_downstream_2mb"]
> ```

FYI not reviewed



_Code quote:_
```Python
    elif results["mode"] == "x_linked":
        # TODO add check for male embryo informative SNPs
        validation = all_validation[results["sample_id"]]
        assert results["mode"] == validation["mode"]
        assert results["sample_id"] == validation["sample_id"]
        assert results["num_snps"] == validation["num_snps"]
        assert results["info_snps_upstream_2mb"] == validation["info_snps_upstream_2mb"]
        assert results["info_snps_in_gene"] == validation["info_snps_in_gene"]
        assert (
            results["info_snps_downstream_2mb"]
            == validation["info_snps_downstream_2mb"]
        )
        assert results["total_info_snps"] == validation["total_info_snps"]
        assert (
            results["high_risk_snps_upstream_2mb"]
            == validation["high_risk_snps_upstream_2mb"]
        )
        assert (
            results["high_risk_snps_within_gene"] == validation["high_risk_within_gene"]
        )
        assert (
            results["high_risk_snps_downstream_2mb"]
            == validation["high_risk_snps_downstream_2mb"]
        )
        assert (
            results["low_risk_snps_upstream_2mb"]
            == validation["low_risk_snps_upstream_2mb"]
        )
        assert (
            results["low_risk_snps_within_gene"] == validation["low_risk_within_gene"]
        )
        assert (
            results["low_risk_snps_downstream_2mb"]
            == validation["low_risk_snps_downstream_2mb"]
        )
```
___
*[`tests/functional/test_snp_filtering.py` line 308 at r5](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJBMGNeEXubqMHSvjDJ:-NJBMGNeEXubqMHSvjDK:b-mqb70t) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/75b69e44ffc1455e8b00188cc7de7201979bd9bf/tests/functional/test_snp_filtering.py#L308)):*
> ```Python
>             == validation["low_risk_downstream_2mb"]
>         )
>     elif result["mode"] == "x_linked":
> ```

FYI not reviewed



_Code quote:_
```Python
    elif result["mode"] == "x_linked":
        assert result["mode"] == validation["mode"]
        assert result["sample_id"] == validation["sample_id"]
        assert result["high_risk,upstream"] == validation["high_risk_upstream_2mb"]
        assert result["high_risk,within_gene"] == validation["high_risk_within_gene"]
        assert result["high_risk,downstream"] == validation["high_risk_downstream_2mb"]
        assert result["low_risk,upstream"] == validation["low_risk_upstream_2mb"]
        assert result["low_risk,within_gene"] == validation["low_risk_within_gene"]
        assert result["low_risk,downstream"] == validation["low_risk_downstream_2mb"]
```


<!-- Sent from Reviewable.io -->

2022-12-13 17:00 UTC, aledj2 reviewed
> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 18 of 65 files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)



<!-- Sent from Reviewable.io -->

2022-12-13 17:29 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 18 of 65 files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith)

___
*[`docs/source/changelog.md` line 3 at r5](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJBX9ym1aFPrZB7nxBM:-NJBX9ym1aFPrZB7nxBN:b7lir76) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/75b69e44ffc1455e8b00188cc7de7201979bd9bf/docs/source/changelog.md#L3)):*
> ```Markdown
> # Changelog
> 
> Initial release
> ```

maybe need to add something here?


<!-- Sent from Reviewable.io -->

2022-12-13 17:30 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 18 of 65 files reviewed, 3 unresolved discussions (waiting on @Graeme-Smith)

___
*[`snp_haplotyper/x_linked_logic.py` line 4 at r5](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJBXMAz0yp7wJQi-M7n:-NJBXMAz0yp7wJQi-M7o:byuz2ti) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/75b69e44ffc1455e8b00188cc7de7201979bd9bf/snp_haplotyper/x_linked_logic.py#L4)):*
> ```Python
> import pandas as pd
> 
> # Logic is the same whether using affected son of carrier or grandmother as reference
> ```

could you add a comment here to say this file has not been code reviewed?


<!-- Sent from Reviewable.io -->

2022-12-13 17:31 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 18 of 65 files reviewed, 4 unresolved discussions (waiting on @Graeme-Smith)

___
*[`snp_haplotyper/excel_templates/SNP_haplotype_template_v1.7.xlsm` line 0 at r5](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJBXXar8-OBJTq2yOfP:-NJBXXar8-OBJTq2yOfQ:b-9i4f22) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/75b69e44ffc1455e8b00188cc7de7201979bd9bf/snp_haplotyper/excel_templates/SNP_haplotype_template_v1.7.xlsm#L0)):*
Can this be renamed in line with the release?


<!-- Sent from Reviewable.io -->

2022-12-14 10:18 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 18 of 65 files reviewed, 4 unresolved discussions (waiting on @aledj2)

___
*[`docs/source/changelog.md` line 3 at r5](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJBX9ym1aFPrZB7nxBM:-NJEzcHp7QvQggtPowGP:b-72z7t7) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/75b69e44ffc1455e8b00188cc7de7201979bd9bf/docs/source/changelog.md#L3)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

maybe need to add something here?
</blockquote></details>

Added descriptive paragraph
___
*[`snp_haplotyper/excel_templates/SNP_haplotype_template_v1.7.xlsm` line  at r5](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJBXXar8-OBJTq2yOfP:-NJF20WRAlF-77UIcRFc:b-7bw8im) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/75b69e44ffc1455e8b00188cc7de7201979bd9bf/snp_haplotyper/excel_templates/SNP_haplotype_template_v1.7.xlsm#L)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Can this be renamed in line with the release?
</blockquote></details>

I'd rather keep the versioning separate:
- There may be confusion with older, similarly named versions of the spreadsheet
- It would cause an issue when doing future releases - do we change the version number of the spreadsheet to match the release version every time, even though nothing might have changed in the spreadsheet being versioned?  Or do we change the spreadsheet version only when it has been change, which would bring us back to a situation like we have now?
___
*[`snp_haplotyper/snp_haplotype.py` line 1284 at r4](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJAtmZcAEXzPJdOq9Go:-NJF8ClX4Cv2jPqRX_YM:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/1057b504422303250ea205e8a94a74d2b66dd268/snp_haplotyper/snp_haplotype.py#L1284)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

comment please
</blockquote></details>

Done.
___
*[`snp_haplotyper/x_linked_logic.py` line 4 at r5](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJBXMAz0yp7wJQi-M7n:-NJF4GOy7R0k2lRErL8l:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/75b69e44ffc1455e8b00188cc7de7201979bd9bf/snp_haplotyper/x_linked_logic.py#L4)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

could you add a comment here to say this file has not been code reviewed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-14 13:40 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 17 of 65 files reviewed, 4 unresolved discussions (waiting on @aledj2)

___
*[`snp_haplotyper/excel_templates/SNP_haplotype_template_v1.7.xlsm` line  at r5](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJBXXar8-OBJTq2yOfP:-NJFhnQc0SpEuyHoTwF_:b-d3tolc) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/75b69e44ffc1455e8b00188cc7de7201979bd9bf/snp_haplotyper/excel_templates/SNP_haplotype_template_v1.7.xlsm#L)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

I'd rather keep the versioning separate:
- There may be confusion with older, similarly named versions of the spreadsheet
- It would cause an issue when doing future releases - do we change the version number of the spreadsheet to match the release version every time, even though nothing might have changed in the spreadsheet being versioned?  Or do we change the spreadsheet version only when it has been change, which would bring us back to a situation like we have now?
</blockquote></details>

Changed to _1.0.0


<!-- Sent from Reviewable.io -->

2022-12-14 14:36 UTC, aledj2 reviewed
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 18 of 65 files reviewed, 2 unresolved discussions



<!-- Sent from Reviewable.io -->

2022-12-15 11:54 UTC, aledj2 reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 18 of 66 files reviewed, all discussions resolved

___
*[`snp_haplotyper/excel_templates/SNP_haplotype_template_v1.7.xlsm` line  at r5](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJBXXar8-OBJTq2yOfP:-NJKYpew-xL1oVLTe5Jt:bficmgs) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/75b69e44ffc1455e8b00188cc7de7201979bd9bf/snp_haplotyper/excel_templates/SNP_haplotype_template_v1.7.xlsm#L)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

appears to be a new file not renamed. Can you delete this one?


<!-- Sent from Reviewable.io -->

2022-12-15 11:56 UTC, aledj2 reviewed
> Reviewed 9 of 53 files at r3, 3 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 30 of 66 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-12-15 11:58 UTC, aledj2 requested changes
> Reviewed 1 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 31 of 66 files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith)

___
*[`snp_haplotyper/config.py` line 19 at r9](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJKdcG98jruegDW_VlI:-NJKdcGAAn43XzbHmAyR:b-88bt9e) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/d32e03ef0ad91168354f8a331185d54751eaf678/snp_haplotyper/config.py#L19)):*
> ```Python
> allow_autosomal_dominant_cases = True
> allow_autosomal_recessive_cases = True
> allow_x_linked_cases = True
> ```

False
___
*[`snp_haplotyper/config.py` line 20 at r9](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJKdefBBtTU9_uZySNy:-NJKdefBBtTU9_uZySNz:b-88bt9e) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/d32e03ef0ad91168354f8a331185d54751eaf678/snp_haplotyper/config.py#L20)):*
> ```Python
> allow_autosomal_recessive_cases = True
> allow_x_linked_cases = True
> allow_consanguineous_cases = True
> ```

False


<!-- Sent from Reviewable.io -->

2022-12-15 12:00 UTC, aledj2 requested changes
> Reviewed 2 of 36 files at r1, 2 of 53 files at r3, 1 of 5 files at r5, 1 of 4 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 38 of 66 files reviewed, 3 unresolved discussions (waiting on @Graeme-Smith)

___
*[`snp_haplotyper/config.py` line 25 at r9](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJKdme2827GIeSsgwEV:-NJKdme2827GIeSsgwEW:bc60fbx) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/d32e03ef0ad91168354f8a331185d54751eaf678/snp_haplotyper/config.py#L25)):*
> ```Python
> # The following flag adds a warning to the report if the version of BASHer used to generate it
> # is still in development
> released_to_production = False
> ```

#TODO!


<!-- Sent from Reviewable.io -->

2022-12-15 13:28 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2)* status: 38 of 66 files reviewed, 3 unresolved discussions (waiting on @aledj2)

___
*[`snp_haplotyper/config.py` line 19 at r9](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJKdcG98jruegDW_VlI:-NJKy0O2ChIldEL4EtUk:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/d32e03ef0ad91168354f8a331185d54751eaf678/snp_haplotyper/config.py#L19)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

False
</blockquote></details>

Done.
___
*[`snp_haplotyper/config.py` line 20 at r9](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJKdefBBtTU9_uZySNy:-NJKy0nH8I7rFBUOPTly:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/d32e03ef0ad91168354f8a331185d54751eaf678/snp_haplotyper/config.py#L20)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

False
</blockquote></details>

Done.
___
*[`snp_haplotyper/config.py` line 25 at r9](https://reviewable.io/reviews/moka-guys/snp_haplotyper/2#-NJKdme2827GIeSsgwEV:-NJKy3hx8eUCEeZVIeWL:b-896fix) ([raw file](https://github.com/moka-guys/snp_haplotyper/blob/d32e03ef0ad91168354f8a331185d54751eaf678/snp_haplotyper/config.py#L25)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

#TODO!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-15 15:36 UTC, merged