Flask frontend - MVP web app
moka-guys/SNP_haplotyper pull request #7
Opened 2023-05-26 10:50 UTC by Graeme-Smith

### 

- Flask frontend created to allow the user to select the sample sheet and SNP array files, automatically run BASHer, and download the HTML report from their web browser.

- Input spreadsheets are now checked programmatically using the check_inputs.py script, with any identified data entry errors being flagged to the user.
- Log files are produced for each run to aid in troubleshooting and for audit purposes.
- PDF files are produced in addition to the HTML files: These files contain:
     - Static plots
     - Report tables were simplified to remove unnecessary information in response to user feedback.
- NoCalls, MisCalls and informative SNPs were removed from summary tables to aid readability.
- For Autosomal Recessive cases the table now groups the entries by ‘snp_inherited_from’ in addition to ‘risk_category’ and ‘gene_position’ as requested in user feedback.
- Plots for different samples are separated by a horizontal line.
- Timestamp added to output report filename for audit purposes and to prevent files from being automatically overwritten every time BASHer is run.
- Web app supports uploading multiple SNP files which are produced by larger runs by automatically concatenating them into a single file before passing to BASHer.  Alternatively the merge_array_files.py script can be run from the command line and passed to the snp_haplotyper.py script directly.  Checks are performed to ensure:
- No duplicate columns are present between the files except for those expected to be, "Probeset ID", “Position”, and “Chr”.
- All files must cover the same region covering identical ProbeSets.
- Supports report generation for pre-cases where only the trios have been sequenced.
- Supports analysis of cases with X-linked mode of inheritance.
- Live feedback to users of the webtool highlighting errors in the sample spreadsheets.

Backend changes:

- Logger support added to produce a log file for each case run.

- Duplication of code calculating subtotal of SNPs per region/category between the tables and the plots have been removed to allow new features to be added and to aid maintainability.
- The modules excel_parser and snp_haplotyper were refactored so that they are callable as modules and not exclusively via the command line.  This makes integration with the web app and test suite simpler.
- Test suite refactored so that it no longer requires the results to be streamed from stdout in JSON where it was then captured and parsed.  This was preventing useful error messages from being sent to stdout and was difficult to maintain as more features are added.
- Pytest code checking outputs moved into module validate_output.py to prevent replication over multiple test modules.
- Type hinting added to functions when appropriate to improve readability, and checked using mypy.
- Created check_inputs.py to flag incorrect data entry and to give feedback to users on data input errors.
- Input files are explicitly filtered for the region of interest before any downstream analysis. 
- Dockerised flask app created to allow the user to run BASHer via a web browser.
- Different docker-compose files for production and development environments

2023-06-09 15:59 UTC, aledj2 requested changes
> Reviewed 1 of 21 files at r1, 1 of 6 files at r2, 1 of 6 files at r4, 11 of 26 files at r5.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7)* status: 14 of 35 files reviewed, 10 unresolved discussions (waiting on @Graeme-Smith)

___
*[`docs/source/deployment.md` line 53 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVLTgY-Imc3xitVyu6:-NXVLTgZ8Q-xcMFm93x5:btko42b) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/docs/source/deployment.md#L53)):*
> ```Markdown
> allow_autosomal_recessive_cases = True
> allow_x_linked_cases = True
> allow_consanguineous_cases = False
> ```

if this is just docs stating how to turn off this functionality shouldn't this still be true? but it's just an example I guess!
___
*[`snp_haplotyper/app.py` line 46 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVT3OwAZ4z3M3Qq83k:-NXVT3OwAZ4z3M3Qq83l:bq8afnp) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L46)):*
> ```Python
> 
> 
> app = Flask(__name__)
> ```

comment?
___
*[`snp_haplotyper/app.py` line 57 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVShMlCUMLyq2U0kj9:-NXVShMlCUMLyq2U0kjA:btwg98q) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L57)):*
> ```Python
> app.config["WTF_CSRF_ENABLED"] = True
> 
> app.config.from_object(__name__)
> ```

any comments for this bit?
___
*[`snp_haplotyper/app.py` line 212 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVboGD6afH-Jg-XlwP:-NXVboGD6afH-Jg-XlwQ:bw9rxby) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L212)):*
> ```Python
> @basher_bp.route("/", methods=["GET", "POST"])
> @cross_origin(supports_credentials=True)
> def form(basher_state="initial"):
> ```

for comments, I think the logic can start from here
___
*[`snp_haplotyper/app.py` line 218 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVcXuv4Ipld6Jp3UHj:-NXVcXuv4Ipld6Jp3UHk:biijt2) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L218)):*
> ```Python
>     chgDetail = dict()
> 
>     if request.method == "POST" and chgForm.validate_on_submit():
> ```

I think validate_on_submit and errors are built in flask functions
___
*[`snp_haplotyper/app.py` line 237 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVd3vH4qArvo1kCYP4:-NXVd3vH4qArvo1kCYP5:brdoipw) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L237)):*
> ```Python
>         logger.addHandler(file_handler)
> 
>         sample_sheet = chgForm.sample_sheet.data
> ```

I think chgform.sample_sheet.data is the filepath given 
then below it's saved with the session details and then added to the chgdetails dict
___
*[`snp_haplotyper/app.py` line 270 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVia5_5-ipHelR0uyY:-NXVia5_5-ipHelR0uyZ:b-uhm7w7) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L270)):*
> ```Python
> 
>         chgDetail["snp_array_files"] = input_file
>         basher_state = "started"
> ```

might make sense later, but is this premature?
___
*[`snp_haplotyper/app.py` line 285 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVsYEBBzw0MfG94bl-:-NXVsYEBBzw0MfG94bl0:b-fh6hyd) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L285)):*
> ```Python
>         )
> 
>         basher_input_namespace, input_errors, input_ok_flag = call_excel_parser(
> ```

pick up from here
___
*[`snp_haplotyper/excel_parser.py` line 1 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVr7wN9NyP6gmVGDGc:-NXVr7wN9NyP6gmVGDGd:bopm5ru) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/excel_parser.py#L1)):*
> ```Python
> import argparse
> ```

double check  understanding/functionality of this script - bit confused by some comments at the bottom about cmd line and spreadsheet (L419)
___
*[`snp_haplotyper/excel_parser.py` line 237 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVpN0W34DHwqHFLYuV:-NXVpN0W34DHwqHFLYuW:b-pfzq24) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/excel_parser.py#L237)):*
> ```Python
> 
>         # Ensure that "embryo_sex" is in lowercase
>         if "embryo_sex" in embryo_data_df.columns:
> ```

I wonder if to make this a little more robust could loop through columns, convert the case and then do the comparison?  - not to do this release.


<!-- Sent from Reviewable.io -->

2023-06-10 11:31 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7)* status: 14 of 35 files reviewed, 18 unresolved discussions (waiting on @Graeme-Smith)

___
*[`snp_haplotyper/app.py` line 212 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVboGD6afH-Jg-XlwP:-NXZRlrr0hfhHHk1ywA-:b-9gqlfd) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L212)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

for comments, I think the logic can start from here
</blockquote></details>

maybe in docstring to say this function is called by the button in the html
___
*[`snp_haplotyper/app.py` line 397 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXZR_V316mjTZH46Ca1:-NXZR_V316mjTZH46Ca2:b-xykgjt) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L397)):*
> ```Python
> @basher_bp.route("/download", methods=["GET", "POST"])
> @cross_origin(supports_credentials=True)
> def download():
> ```

maybe a docstring here to say this is controlled by the download button in the html?
___
*[`snp_haplotyper/config.py` line 24 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXZyz9l6nFjv0DXek9b:-NXZyz9l6nFjv0DXek9c:b2xgjpw) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/config.py#L24)):*
> ```Python
> 
> # Filepaths used by the excel_parser.py script
> output_folder = "/home/graeme/Desktop/SNP_haplotyper/output"
> ```

are these used?
___
*[`snp_haplotyper/snp_haplotype.py` line 1299 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXZUAzp3mCA7HHifKr7:-NXZUAzp3mCA7HHifKr8:brgxm6b) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_haplotype.py#L1299)):*
> ```Python
> 
>     # Add column describing how far the SNP is from the gene of interest
>     df = annotate_distance_from_gene(df, args.chr, int(args.gene_start), args.gene_end)
> ```

if gene_start needs to be converted to int does gene_end not too?
___
*[`snp_haplotyper/snp_haplotype.py` line 1304 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXZUkHu1-s44R1KPEPE:-NXZUkHu1-s44R1KPEPF:bas3m5k) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_haplotype.py#L1304)):*
> ```Python
>     df = add_rsid_column(df, affy_2_rs_ids_df)
> 
>     # Calculate qc metrics before filtering out Nocalls TODO: remove dependency on embryo.ids
> ```

are TODOs captured in issues?
___
*[`snp_haplotyper/snp_haplotype.py` line 1545 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXZyEda-na6FwiUiawL:-NXZyEda-na6FwiUiawM:b-nfwk2x) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_haplotype.py#L1545)):*
> ```Python
>         "summary_embryo_table": summary_embryo_table if args.trio_only == False else "",
>         "summary_embryo_by_region_table": summary_embryo_by_region_table
>         if args.trio_only == False
> ```

formatting - split across multiple rows
___
*[`snp_haplotyper/snp_plot.py` line 193 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NX_2zQ8891J0WGflwC1:-NX_2zQ8891J0WGflwC2:b-q82x8e) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_plot.py#L193)):*
> ```Python
>                     name=annotation_name_high_risk,
>                     x=[
>                         gene_start - (flanking_region_size - 100000),
> ```

should this beflanking region size + 100000? (like on line 169)
___
*[`snp_haplotyper/snp_plot.py` line 195 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NX_3Dzz2uUzP42-Nu1K:-NX_3Dzz2uUzP42-Nu1L:b-no3ome) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_plot.py#L195)):*
> ```Python
>                         gene_start - (flanking_region_size - 100000),
>                         (gene_start + gene_end) / 2,
>                         gene_end + (flanking_region_size - 100000),
> ```

likewise, shouldn't this be a +?
___
*[`snp_haplotyper/snp_plot.py` line 219 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NX_3JiBAwkk6doK28oe:-NX_3JiBAwkk6doK28of:b-qq7fez) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_plot.py#L219)):*
> ```Python
>                     name=annotation_name_low_risk,
>                     x=[
>                         gene_start - (flanking_region_size - 100000),
> ```

+ or -?
___
*[`snp_haplotyper/snp_plot.py` line 221 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NX_3N8698DxD7FeyNXU:-NX_3N8698DxD7FeyNXV:b-qq7fez) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_plot.py#L221)):*
> ```Python
>                         gene_start - (flanking_region_size - 100000),
>                         (gene_start + gene_end) / 2,
>                         gene_end + (flanking_region_size - 100000),
> ```

+ or -?


<!-- Sent from Reviewable.io -->

2023-06-21 16:25 UTC, aledj2 requested changes
> Reviewed 1 of 9 files at r3, 2 of 26 files at r5.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7)* status: 17 of 35 files reviewed, 30 unresolved discussions (waiting on @Graeme-Smith)

___
*[`snp_haplotyper/check_inputs.py` line 20 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTeabS3CmKq-7_9TjM:-NYTeabS3CmKq-7_9TjN:b-z10plc) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L20)):*
> ```Python
> 
> # Create an error dictionary
> error_dict = {}
> ```

my brain may have melted by this point in the day but if the check_input function is called, does this get initiated?
___
*[`snp_haplotyper/check_inputs.py` line 62 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTdjNODMyMnCHZL_d9:-NYTdjNPAgXNENFzSh_e:bjh3oo6) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L62)):*
> ```Python
>         input_ok_flag = False
> 
>     if input_namespace.chr not in [
> ```

case sensitive? or is this controlled elsewhere?
___
*[`snp_haplotyper/check_inputs.py` line 111 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTf0RS0-fazEfwkY_y:-NYTf0RT1fC6FvWcjaBN:b-2e8dlx) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L111)):*
> ```Python
> 
>     # Check if flanking_region_size is "2mb" or "3mb"
>     if input_namespace.flanking_region_size not in ["2mb", "3mb"]:
> ```

are these given as options somewhere to protect against types etc?
___
*[`snp_haplotyper/check_inputs.py` line 181 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTiVme72s_NhgM4mrf:-NYTiVme72s_NhgM4mrg:bz2lj86) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L181)):*
> ```Python
>             input_ok_flag = False
> 
>     allowable_values = {
> ```

is this something that could sit in the config?
___
*[`snp_haplotyper/check_inputs.py` line 199 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTgOpgCTYtxMqHv6Ig:-NYTgOpgCTYtxMqHv6Ih:blu1cnc) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L199)):*
> ```Python
>             "reference_status": {"affected", "unaffected"},
>             "reference_relationship": {
>                 "grandparent",
> ```

Assume cousins/aunts/uncles etc have never come up?
___
*[`snp_haplotyper/check_inputs.py` line 270 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTglnN8elvb0Wlh6sp:-NYTglnN8elvb0Wlh6sq:bykrqgn) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L270)):*
> ```Python
>         "male_partner_status", []
>     ):
>         raise ValueError(
> ```

I don't think valueerrors have been raised before now, they are just logged, assume this is on purpose?
___
*[`snp_haplotyper/check_inputs.py` line 278 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTgxF98-cFhOzgTtt2:-NYTgxF98-cFhOzgTtt3:b-98kmlx) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L278)):*
> ```Python
>         "female_partner_status", []
>     ):
>         raise ValueError(
> ```

not logged?
___
*[`snp_haplotyper/check_inputs.py` line 288 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTh3Oe19YcLdKyQPr1:-NYTh3OfE6XgBS7vJf9E:b-98kmlx) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L288)):*
> ```Python
>         and input_namespace.female_partner_status == "unaffected_partner"
>     ):
>         raise ValueError(
> ```

not logged?
___
*[`snp_haplotyper/check_inputs.py` line 292 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTh9G8CCQGMIPxOlc5:-NYTh9G8CCQGMIPxOlc6:b-j4msj6) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L292)):*
> ```Python
>         )
> 
>     return error_dict, input_ok_flag
> ```

i'm missing where error_dict is populated
___
*[`snp_haplotyper/merge_array_files.py` line 48 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTkT8V-1xbLxUmcZJq:-NYTkT8V-1xbLxUmcZJr:bft7ayh) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/merge_array_files.py#L48)):*
> ```Python
> 
> 
> def check_input_dfs(dfs: list[pd.DataFrame]) -> None:
> ```

I'm not familiar with this, what is it? Similar on other functions in this script
___
*[`snp_haplotyper/snp_haplotype.py` line 317 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTl18094TXoGTNWJNn:-NYTl18094TXoGTNWJNo:b-u69yxi) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_haplotype.py#L317)):*
> ```Python
>         region_start = int(gene_start) - 3000000
>         region_end = int(gene_end) + 3000000
>     df = df[df["Position"] >= region_start]
> ```

df is being written to twice here? or is it being filtered twice?
___
*[`snp_haplotyper/snp_haplotype.py` line 1062 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTlXPpELyPyxsB0n4P:-NYTlXPpELyPyxsB0n4Q:bv050ak) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_haplotype.py#L1062)):*
> ```Python
>         # rather than say sum(). reset_index() converts it from a groupby object with two indexes,
>         # gene_distance and risk_category into one index of "gene_distance, risk_category".
>         if "snp_inherited_from" in df:
> ```

got to here


<!-- Sent from Reviewable.io -->

2023-06-23 14:50 UTC, aledj2 requested changes
> Reviewed 1 of 21 files at r1, 1 of 9 files at r3, 5 of 26 files at r5.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7)* status: 24 of 35 files reviewed, 32 unresolved discussions (waiting on @Graeme-Smith)

___
*[`snp_haplotyper/snp_haplotype.py` line 317 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTl18094TXoGTNWJNn:-NYcRh0T58z--kUilyYR:bcgio73) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_haplotype.py#L317)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

df is being written to twice here? or is it being filtered twice?
</blockquote></details>

I think filtered 
___
*[`snp_haplotyper/validate_output.py` line 37 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYccTKr36Sx1w79lHRi:-NYccTKr36Sx1w79lHRj:bbn9ezn) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/validate_output.py#L37)):*
> ```Python
>         assert (
>             lookup_df_result(
>                 summary_snps_by_region, "snp_count", gene_distance="within_gene"
> ```

Can you add some comments please? Just so I can get a feel for what is returned when gene_distance = "within gene" or "start" etc
___
*[`snp_haplotyper/validate_output.py` line 435 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYcgi9A6VnHRrlWXJY9:-NYcgi9A6VnHRrlWXJYA:bg7icnt) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/validate_output.py#L435)):*
> ```Python
>                 risk_category="low_risk",
>             )
>             == validation["low_risk_snps_downstream_2mb_from_male"]
> ```

within this script 2mb is used. Does the new support for 2mb or 3mb break this?
___
*[`tests/functional/test_excel_import.py` line 63 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYciaAiEoE61loW9d1l:-NYciaAiEoE61loW9d1m:bdencjz) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/tests/functional/test_excel_import.py#L63)):*
> ```Python
> 
> @pytest.mark.parametrize("name", setup_test_data_from_excel(False, version=1))
> def test_informative_snps_excel_v1(name):
> ```

I'm not sure if I need to fully review the test scripts - I'll go through them now, but I could do with some comments or some docstrings describing what they are testing, or maybe how?


<!-- Sent from Reviewable.io -->

2023-07-21 17:26 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7)* status: 24 of 35 files reviewed, 31 unresolved discussions (waiting on @aledj2)

___
*[`docs/source/deployment.md` line 53 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVLTgY-Imc3xitVyu6:-N_s01ViCSoRNGMCRRoy:bb7lp6m) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/docs/source/deployment.md#L53)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

if this is just docs stating how to turn off this functionality shouldn't this still be true? but it's just an example I guess!
</blockquote></details>

Ammended
___
*[`snp_haplotyper/app.py` line 46 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVT3OwAZ4z3M3Qq83k:-N_s26_q8fIUbH6PCj2d:b8bpu82) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L46)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

comment?
</blockquote></details>

I've added comments
___
*[`snp_haplotyper/app.py` line 57 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVShMlCUMLyq2U0kj9:-N_s2xV88jA_MwYlGzXF:b-8b11j9) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L57)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

any comments for this bit?
</blockquote></details>

Added
___
*[`snp_haplotyper/app.py` line 212 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVboGD6afH-Jg-XlwP:-N_s6QcV7l4i8r5iSTTe:be17soe) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L212)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

maybe in docstring to say this function is called by the button in the html
</blockquote></details>

I added a docstring
___
*[`snp_haplotyper/app.py` line 218 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVcXuv4Ipld6Jp3UHj:-N_ssGNx8p6KpYvIQLlz:bg8zp74) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L218)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I think validate_on_submit and errors are built in flask functions
</blockquote></details>

Yes built in functions - they do a lot of the heavy lifting ensuring input data is sesnible.
___
*[`snp_haplotyper/app.py` line 237 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVd3vH4qArvo1kCYP4:-N_ssStGDYzDPNgjzbXF:b-km7q7) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L237)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I think chgform.sample_sheet.data is the filepath given 
then below it's saved with the session details and then added to the chgdetails dict
</blockquote></details>

Its saved with the session details to avoid duplicate files from other users/sessions - temporary files are saved so that they can be passed to the backend.
___
*[`snp_haplotyper/app.py` line 270 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVia5_5-ipHelR0uyY:-N_sssqI4k9VWzTG1EyC:b-q5ohgs) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L270)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

might make sense later, but is this premature?
</blockquote></details>

This doesn't refer to the backend starting, rather that the data has been submit and controls the flow in the html
___
*[`snp_haplotyper/app.py` line 397 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXZR_V316mjTZH46Ca1:-N_tLao25hHpgBhMpUuC:b-896fjx) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L397)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

maybe a docstring here to say this is controlled by the download button in the html?
</blockquote></details>

Done
___
*[`snp_haplotyper/check_inputs.py` line 20 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTeabS3CmKq-7_9TjM:-N_tO_QR4f000j2E_O5y:behgiaq) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L20)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

my brain may have melted by this point in the day but if the check_input function is called, does this get initiated?
</blockquote></details>

I'll add a comment as it is confusing.   I originally had this script called using os - I now have it imported as a module  - so this code is not used to set the error_dict which is now done in app.py
I'll keep this code for present as I need to check what the commandline version uses.
___
*[`snp_haplotyper/check_inputs.py` line 62 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTdjNODMyMnCHZL_d9:-N_sm24zCk1DHZAjJQXf:b-yaei0z) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L62)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

case sensitive? or is this controlled elsewhere?
</blockquote></details>

Its controlled when the data is imported from the excel sheet
___
*[`snp_haplotyper/check_inputs.py` line 111 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTf0RS0-fazEfwkY_y:-N_tAYYfAg0LleYvR-w9:b-hkn8bm) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L111)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

are these given as options somewhere to protect against types etc?
</blockquote></details>

Argparse 
___
*[`snp_haplotyper/check_inputs.py` line 181 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTiVme72s_NhgM4mrf:-N_tQOpr9rDaMyr29kCn:b-wv06k2) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L181)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is this something that could sit in the config?
</blockquote></details>

Its unlikely to change and when I tried importing it from a config file it made it difficult to read the code.
___
*[`snp_haplotyper/check_inputs.py` line 199 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTgOpgCTYtxMqHv6Ig:-N_s6blaDz0bRvdkjHld:bixznj) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L199)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Assume cousins/aunts/uncles etc have never come up?
</blockquote></details>

No, they have never been covered in the logic as the PGD team would not use thm as references.
___
*[`snp_haplotyper/check_inputs.py` line 270 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYTglnN8elvb0Wlh6sp:-N_s8Ece4KaD4DyTKxXU:b2zp013) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/check_inputs.py#L270)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I don't think valueerrors have been raised before now, they are just logged, assume this is on purpose?
</blockquote></details>

I capture these value errors and pass them back to the user in realtime as a popup warning message - they are related to common input eror [...]

2023-07-26 09:15 UTC, aledj2 requested changes
> Reviewed 2 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7)* status: 23 of 44 files reviewed, 6 unresolved discussions (waiting on @Graeme-Smith)

___
*[`snp_haplotyper/app.py` line 237 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVd3vH4qArvo1kCYP4:-NaGRiWw8XqaX14zKOBb:bykubge) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L237)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Its saved with the session details to avoid duplicate files from other users/sessions - temporary files are saved so that they can be passed to the backend.
</blockquote></details>

Can responses like this be added as comments?
___
*[`snp_haplotyper/app.py` line 270 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVia5_5-ipHelR0uyY:-NaGRmVN-2qrOvV9V6B0:bykubge) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L270)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

This doesn't refer to the backend starting, rather that the data has been submit and controls the flow in the html
</blockquote></details>

Can responses like this be added as comments?
___
*[`snp_haplotyper/snp_plot.py` line 193 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NX_2zQ8891J0WGflwC1:-NaGSsNw6Ay9xPIkoRMf:bykubge) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_plot.py#L193)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

This is basically where to nicely place the annotation text within the plot - it took a bit of trial and error to get the text in an appropriate place not overlapping other info in the plot
</blockquote></details>

Can responses like this be added as comments?
___
*[`snp_haplotyper/snp_plot.py` line 195 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NX_3Dzz2uUzP42-Nu1K:-NaGSuMO8AHGVUK9BFcs:b-jrdkny) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_plot.py#L195)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

This is basically where to nicely place the annotation text within the plot - it took a bit of trial and error to get the text in an appropriate place not overlapping other info in the plot
</blockquote></details>

Can responses like this be added as comments? 
___
*[`snp_haplotyper/snp_plot.py` line 219 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NX_3JiBAwkk6doK28oe:-NaGTDlr1WkbRsh57evl:bykubge) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_plot.py#L219)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

This is basically where to nicely place the annotation text within the plot - it took a bit of trial and error to get the text in an appropriate place not overlapping other info in the plot
</blockquote></details>

Can responses like this be added as comments?
___
*[`snp_haplotyper/snp_plot.py` line 221 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NX_3N8698DxD7FeyNXU:-NaGTEd2CgtCGM45vFL1:bykubge) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_plot.py#L221)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

This is basically where to nicely place the annotation text within the plot - it took a bit of trial and error to get the text in an appropriate place not overlapping other info in the plot
</blockquote></details>

Can responses like this be added as comments?
___
*[`snp_haplotyper/validate_output.py` line 435 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYcgi9A6VnHRrlWXJY9:-NaGTQGY6cS6adxbjOWm:b3kre) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/validate_output.py#L435)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

I will check this
</blockquote></details>

?


<!-- Sent from Reviewable.io -->

2023-07-27 11:03 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7)* status: 23 of 44 files reviewed, 6 unresolved discussions (waiting on @aledj2)

___
*[`snp_haplotyper/app.py` line 237 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVd3vH4qArvo1kCYP4:-NaLxvg98VFd-6qCXM_r:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L237)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Can responses like this be added as comments?
</blockquote></details>

Done.
___
*[`snp_haplotyper/app.py` line 270 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NXVia5_5-ipHelR0uyY:-NaLy2TgD5qgxTjDTQtY:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/app.py#L270)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Can responses like this be added as comments?
</blockquote></details>

Done.
___
*[`snp_haplotyper/snp_plot.py` line 195 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NX_3Dzz2uUzP42-Nu1K:-NaLyPot2L0hCiynNF1s:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_plot.py#L195)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Can responses like this be added as comments? 
</blockquote></details>

Done.
___
*[`snp_haplotyper/snp_plot.py` line 219 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NX_3JiBAwkk6doK28oe:-NaLyR9b9j5ITaDqOwsW:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_plot.py#L219)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Can responses like this be added as comments?
</blockquote></details>

Done.
___
*[`snp_haplotyper/snp_plot.py` line 221 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NX_3N8698DxD7FeyNXU:-NaLyTm_9S6mOyR2MrIB:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_plot.py#L221)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Can responses like this be added as comments?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-01 16:02 UTC, aledj2 requested changes
> Reviewed 5 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7)* status: 28 of 44 files reviewed, 4 unresolved discussions (waiting on @Graeme-Smith)

___
*[`snp_haplotyper/snp_plot.py` line 195 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NX_3Dzz2uUzP42-Nu1K:-NalpWPZAFtTAH5QS-6B:b-j2we0h) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_plot.py#L195)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry don't think these changes have been pushed/commited?


<!-- Sent from Reviewable.io -->

2023-08-02 13:04 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7)* status: 26 of 44 files reviewed, 4 unresolved discussions (waiting on @aledj2)

___
*[`snp_haplotyper/snp_plot.py` line 195 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NX_3Dzz2uUzP42-Nu1K:-NaqLGthAxKsgaRUuPCP:b-a9i4nm) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/snp_plot.py#L195)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

sorry don't think these changes have been pushed/commited?
</blockquote></details>

I've pushed these now.
___
*[`snp_haplotyper/validate_output.py` line 435 at r5](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7#-NYcgi9A6VnHRrlWXJY9:-NaqL5lh0bT4-5L1kUa_:bwyubx5) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/06331bd08050645ee9f19cf75b99629ba610a0e1/snp_haplotyper/validate_output.py#L435)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

?
</blockquote></details>

Will be done in separate branch and added to individual pull request


<!-- Sent from Reviewable.io -->

2023-08-02 15:45 UTC, aledj2 reviewed
> Reviewed 1 of 21 files at r1, 2 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7)* status: 29 of 44 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-02 15:45 UTC, aledj2 approved these changes
> Reviewed 1 of 9 files at r3, 3 of 26 files at r5, 9 of 11 files at r6, 1 of 6 files at r7, 1 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Graeme-Smith)



<!-- Sent from Reviewable.io -->

2023-08-02 15:46 UTC, merged