BASHer Version 2.0
moka-guys/SNP_haplotyper pull request #9
Opened 2024-01-11 10:08 UTC by Graeme-Smith

**Changelog BASHer 2.0**

Major refactor of the codebase from Version 1.0.  Adds a Flask frontend and support for X-linked cases and consanguineous autosomal recessive cases.

**Frontend changes:**

- A flask frontend created to allow the user to select the sample sheet and SNP array files, automatically run BASHer, and download the HTML report from their web browser.
- Input spreadsheets are now checked programmatically using the check_inputs.py script, with any identified data entry errors being flagged to the user.
- Log files are produced for each run to aid in troubleshooting and for audit purposes.
- PDF files are produced in addition to the HTML files.  This was to fulfil a user's need to have reports which they can annotate. These files contain:
   - Static plots
- Report tables were simplified to remove unnecessary information in response to user feedback.
   - NoCalls, MisCalls and informative SNPs were removed from summary tables to aid readability.
   - For Autosomal Recessive cases the table now groups the entries by ‘snp_inherited_from’ in addition to ‘risk_category’ and ‘gene_position’ as requested in user feedback.
- Timestamp added to output report filename for audit purposes and to prevent files from being automatically overwritten every time BASHer is run.
- Web app supports uploading multiple SNP files which are produced by larger runs by automatically concatenating them into a single file before passing to BASHer.  Alternatively the merge_array_files.py script can be run from the command line and passed to the snp_haplotyper.py script directly.  Checks are performed to ensure:
   - No duplicate columns are present between the files except for those expected to be, "Probeset ID", “Position”, and “Chr”.
   - All files must cover the same region covering identical ProbeSets.
- Supports report generation for pre-cases where only the trios have been sequenced.
- Supports analysis of cases with X-linked mode of inheritance.
   - Includes support for male and female references.
   - Separate informative SNP metrics produced for Female and Male embryos.
- Additional support added for autosomal recessive consanguineous cases.

**Backend changes:**
- Logger support added to produce a log file for each case run.
- Refactored code in an object oriented manner so that it is easier to maintain and open to extension.
- Enum classes added to replace strings to hold several input values where inputs need to be constrained.  This protects against errors in conditional statements due to typos.
- Backend now uses Pandera and Pydantic to validate input data.
- Duplication of code calculating subtotal of SNPs per region/category between the tables and the plots have been removed to allow new features to be added and to aid maintainability.
- The modules excel_parser and snp_haplotyper were refactored so that they are callable as modules and not exclusively via the command line.  This makes integration with the web app and test suite simpler.
- Test suite refactored so that it no longer requires the results to be streamed from stdout in JSON where it was then captured and parsed.  This was preventing useful error messages from being sent to stdout and was difficult to maintain as more features are added.
- Pytest code checking outputs moved into module validate_output.py to prevent replication over multiple test modules.
- Type hinting added when appropriate to improve readability, and to detect type errors faster (when writing the code rather than at runtime).
- Created check_inputs.py to flag incorrect data entry and to give feedback to users on data input errors.
- Input files are explicitly filtered for the region of interest before any downstream analysis. 
- Dockerised flask app created to allow the user to run BASHer via a web browser.
- Different docker-compose files for production and development environments
- Simplify code for displaying figures in plots
- Supports analysis of cases with X-linked mode of inheritance including when reference is female.
- Separate Informative SNPs for Male & Female
- Additional support for autosomal recessive consanguineous cases. 
- Excel template updated to match current workflow
- Checking module added to excel_parser
   - Add checking for mode of inheritance specific values
   - Check file names to imported files
- NoCalls are now divided into “NoCall” and “NoCall_in_trio” to separate two different bits of data which were being grouped together:
   - “NoCall” is where there is a NoCall in the input data, and is used as a QC metric.
   - “NoCall_in_trio” is called in the embryo if there is a NoCall in the trio at that location meaning no inferences can be made.  This separation of two different issues by using more precise terminology makes the reports clearer.  Previously the report grouped this data together meaning that the total number of NoCalls differed between sections of the report. 
- Filters input data based on the file CytoScan_HT_CMA_variants.csv to exclude any SNPs on the array which are used to call pathogenic variants in order to avoid incidental findings (NOTE: These should already be removed downstream of BASHer).
- Filters out probesets which do not refer to a single SNP based on the file TODO
- A column for affy_snp_id is added to the SNP array descriptive file to identify multiple probesets which relate to the same SNP.  This is then used by BASHer to avoid counting multiple probesets as independent pieces of data by:
   - Amalgamating the data from multiple probesets into one entry if all results for that particular location are identical.
   - Discarding all the data for that location if there is disagreement between the various probes for a single location.
- Code has been refactored to be amenable to adding future support for a Region of Interest greater than 2Mb (essentially any integer value for MBs upstream/downstream).  Not yet implemented due to lack of data to validate.

2024-02-20 16:47 UTC, RachelDuffin requested changes
> Reviewed 16 of 51 files at r1, 8 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9)* status: 24 of 51 files reviewed, 22 unresolved discussions (waiting on @Graeme-Smith and @rebeccahaines1)

___
*[`Makefile` line 20 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0T7ZrAa0VOokywLaA:-Nr0T7ZrAa0VOokywLaB:b-i9wnlo) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/Makefile#L20)):*
> ```Makefile
> build:
> 	docker buildx build --build-arg IMG_VERSIONED=$(IMG_VERSIONED) --platform linux/amd64 -t $(IMG_VERSIONED) . || \
> 	docker build  --build-arg IMG_VERSIONED=$(IMG_VERSIONED) -t $(IMG_VERSIONED) .
> ```

Suggestion to add a docker save command to the Makefile to standardise the saving of the image to a zip file. e.g.: https://github.com/moka-guys/duty_csv/blob/main/Makefile
___
*[`docs/source/development.md` line 136 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0jGdW6pjvHliG8roR:-Nr0jGdW6pjvHliG8roS:bdha6z6) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/docs/source/development.md#L136)):*
> ```Markdown
> ## Release Process
> 
> TODO
> ```

Should this TODO be here?
___
*[`snp_haplotyper/app.py` line 69 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0jgoLAuGW32KEyTSg:-Nr0jgoLAuGW32KEyTSh:b-e0l11a) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/app.py#L69)):*
> ```Python
> IMG_VERSIONED = os.getenv(
>     "IMG_VERSIONED", "N/A"
> )  # Get the version of the application for display in
> ```

Incomplete comment
___
*[`snp_haplotyper/check_inputs.py` line 138 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0k0rcE3irn_tv0G34:-Nr0k0rcE3irn_tv0G35:b-10n9ms) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/check_inputs.py#L138)):*
> ```Python
>         input_ok_flag = False
> 
>     # # Check if ref_relationship is a non-empty string
> ```

Should these lines of code be commented out? Or removed?
___
*[`snp_haplotyper/check_inputs.py` line 228 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0k8HI1LPrsMnpbE_t:-Nr0k8HI1LPrsMnpbE_u:b-vixh63) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/check_inputs.py#L228)):*
> ```Python
>     }
> 
>     # # Check if reference_status is an allowable value based on the mode_of_inheritance
> ```

Should these lines be commented out? Or emoved
___
*[`snp_haplotyper/check_inputs.py` line 271 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0kBDi5w6pt_RAGG46:-Nr0kBDi5w6pt_RAGG47:b-llpahm) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/check_inputs.py#L271)):*
> ```Python
>     )
> 
>     # # Check if the male_partner_status is allowable for the current mode of inheritance
> ```

Should these lines be commented out? or removed?
___
*[`snp_haplotyper/classes_snp_haplotyper.png` line 0 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0qNjVA5x4Qe2b14Ah:-Nr0qNjc7uNFY_Vz7RtO:b6q0y5u) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/classes_snp_haplotyper.png#L0)):*
I have had a quick look at this class diagram and it seems like it does not map all the relationships between classes?

e.g. https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPDataClass.py#L512C31-L524C1

But there is no relationship mapped between InheritanceLogicFactory and AutosomalDominantLogic
___
*[`snp_haplotyper/EmbryoDataClass.py` line 23 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6Cd2r0ivLeYxdcWwN:-Nr6Cd2r0ivLeYxdcWwO:bca623b) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L23)):*
> ```Python
> 
> 
> class EmbryoAlleleCategorizer(ABC):
> ```

Please can you add a class docstring. E.g. https://github.com/moka-guys/automate_demultiplex/blob/833445d3773e5408905410eb8331ab4f0c3ef64a/demultiplex/demultiplex.py#L34-L67

It  makes it a lot easier for someone picking up the code to understand what the class attributes and methods are / their types
___
*[`snp_haplotyper/EmbryoDataClass.py` line 47 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6Cke883c384KufyKV:-Nr6Cke883c384KufyKW:bwalell) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L47)):*
> ```Python
> 
>     @abstractmethod
>     def categorize(self, *args, **kwargs):
> ```

Please can you add a docstring
___
*[`snp_haplotyper/EmbryoDataClass.py` line 51 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6CgZ64pjm3wLrVnUc:-Nr6CgZ64pjm3wLrVnUd:bar7tz5) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L51)):*
> ```Python
> 
> 
> class AutosomalDominantCategorizer(EmbryoAlleleCategorizer):
> ```

Please can you add a class docstring
___
*[`snp_haplotyper/EmbryoDataClass.py` line 88 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6Du6J4urC11512CxX:-Nr6Du6J4urC11512CxY:bar7tz5) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L88)):*
> ```Python
> 
> 
> class AutosomalRecessiveCategorizer(EmbryoAlleleCategorizer):
> ```

Please can you add a class docstring
___
*[`snp_haplotyper/EmbryoDataClass.py` line 182 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6CxFs0nn_yEjO0sr9:-Nr6CxFs0nn_yEjO0srA:bar7tz5) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L182)):*
> ```Python
> 
> 
> class XLinkedCategorizer(EmbryoAlleleCategorizer):
> ```

Please can you add a class docstring
___
*[`snp_haplotyper/EmbryoDataClass.py` line 693 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6E0yy9uBQZw28rl9F:-Nr6E0yy9uBQZw28rl9G:bar7tz5) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L693)):*
> ```Python
> 
> @dataclass
> class EmbryoData:
> ```

Please can you add a class docstring
___
*[`snp_haplotyper/EmbryoDataClass.py` line 779 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6F-jhAMuOHZS6qJhh:-Nr6F-jhAMuOHZS6qJhi:b8e5iu8) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L779)):*
> ```Python
>         )
> 
>     def get_embryo_results(self):
> ```

Why do you need a function that returns a class attribute? You should be able to just access it from the class directly e.g. 

embryo_data = EmbryoData()
embryo_data.embryo_category_df
___
*[`snp_haplotyper/EmbryoDataClass.py` line 782 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6FHTz54Z7Y1ORqbEJ:-Nr6FHTz54Z7Y1ORqbEK:b-ya81ng) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L782)):*
> ```Python
>         return self.embryo_category_df
> 
>     def get_pytest_benchmark(self):
> ```

Same as above
___
*[`snp_haplotyper/EnumDataClasses.py` line 31 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6HFR47zv_BQ3UWtTh:-Nr6HFR47zv_BQ3UWtTi:b2qhrm5) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EnumDataClasses.py#L31)):*
> ```Python
>     MALE = "male"
>     FEMALE = "female"
>   [...]

2024-02-21 15:10 UTC, RachelDuffin requested changes
> Reviewed 26 of 51 files at r1, 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9)* status: all files reviewed, 54 unresolved discussions (waiting on @Graeme-Smith and @rebeccahaines1)

___
*[`snp_haplotyper/inheritance_logic.py` line 35 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArrLjCVHJfh_vWr1F:-NrArrLjCVHJfh_vWr1G:bcyated) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L35)):*
> ```Python
> 
>     def add_nocall_lookup(self):
>         self.nocall_data = f"""
> ```

Would data like this be better stored in a separate csv file and read in?
___
*[`snp_haplotyper/inheritance_logic.py` line 108 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrAqCCvDdUez6OTNYae:-NrAqCCvDdUez6OTNYaf:bwvdsjl) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L108)):*
> ```Python
>         return lookup_df
> 
>     def get_results(self):
> ```

Same as above - is this needed when it can be accessed from the object directly
___
*[`snp_haplotyper/inheritance_logic.py` line 261 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrAqjpTDqcBcTLqauSq:-NrAqjpTDqcBcTLqauSr:b-xd4thj) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L261)):*
> ```Python
>         # Additional initialization for XLinkedLogic
> 
>         self.df = df
> ```

Do you need to reassign these? pretty sure you should be able to access them by self.carrier_female_partner for example - I may be wrong though
___
*[`snp_haplotyper/inheritance_logic.py` line 332 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArzV1-oGqdXQmeYs-:-NrArzV1-oGqdXQmeYs0:bcyated) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L332)):*
> ```Python
>         # Reference_status: affected
>         # Reference_relationship: grandparent
>         self.data = """
> ```

Would data like this be better stored in a separate csv file and read in?
___
*[`snp_haplotyper/inheritance_logic.py` line 370 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrAs2FIEuzJYK76L6bA:-NrAs2FIEuzJYK76L6bB:bcyated) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L370)):*
> ```Python
>         # Reference_status: unaffected
>         # Reference_relationship: grandparent
>         self.data = """
> ```

Would data like this be better stored in a separate csv file and read in?
___
*[`snp_haplotyper/inheritance_logic.py` line 408 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrAs3cY5dqw5wpPncAn:-NrAs3cY5dqw5wpPncAo:bcyated) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L408)):*
> ```Python
>         # Reference_status: affected
>         # Reference_relationship: child or embryo
>         self.data = """
> ```

Would data like this be better stored in a separate csv file and read in?
___
*[`snp_haplotyper/inheritance_logic.py` line 446 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrAs4uv2PD76Sa2ieru:-NrAs4uv2PD76Sa2ierv:bcyated) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L446)):*
> ```Python
>         # Reference_status: unaffected
>         # Reference_relationship: child or embryo
>         self.data = """
> ```

Would data like this be better stored in a separate csv file and read in?
___
*[`snp_haplotyper/inheritance_logic.py` line 522 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrAs6RbCsnQy5gzCmAV:-NrAs6RbCsnQy5gzCmAW:bcyated) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L522)):*
> ```Python
>         # Reference_status: affected
>         # Consanguineous: False
>         self.data = """
> ```

Would data like this be better stored in a separate csv file and read in?
___
*[`snp_haplotyper/inheritance_logic.py` line 560 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrAs7eR5VgLZQXa_N7L:-NrAs7eR5VgLZQXa_N7M:bcyated) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L560)):*
> ```Python
>         # Reference_status: affected
>         # Consanguineous: True
>         self.data = """
> ```

Would data like this be better stored in a separate csv file and read in?
___
*[`snp_haplotyper/inheritance_logic.py` line 597 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrAs9CJ0MJz-mhZsf5i:-NrAs9CJ0MJz-mhZsf5j:bcyated) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L597)):*
> ```Python
>         # InheritanceMode: X-linked
>         # Reference_sex: Male
>         self.data = """
> ```

Would data like this be better stored in a separate csv file and read in?
___
*[`snp_haplotyper/inheritance_logic.py` line 634 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrAsATi7th4LSNFTJV6:-NrAsATi7th4LSNFTJV7:bcyated) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L634)):*
> ```Python
>         # InheritanceMode: X-linked
>         # Reference_sex: Female
>         self.data = """
> ```

Would data like this be better stored in a separate csv file and read in?
___
*[`snp_haplotyper/ReportDataClass.py` line 59 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArG-c7QxGWCo2N6AE:-NrArG-c7QxGWCo2N6AF:b-1w4t95) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/ReportDataClass.py#L59)):*
> ```Python
>     def __post_init__(self):
>         # Format gene_start and gene_end with 1000s comma separator
>         # self.gene_start = f"{int(self.gene_start):,}" # TODO check if already comma separated
> ```

Do you need to address these TODOs?
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 13 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArJ9x8vVjhETnuWRj:-NrArJ9x8vVjhETnuWRk:bnwssq7) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPAnalysisClass.py#L13)):*
> ```Python
> from typing import Any, Dict, List, Optional, Union
> 
> import config as config  # TODO add code to use this dependency
> ```

Do you need to address this TODO?
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 440 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArMZS2B0IBnkAm1al:-NrArMZT2psRtTRxm5uJ:bnwssq7) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPAnalysisClass.py#L440)):*
> ```Python
>             This method does not return anything. It modifies the snp_data DataFrame in-place.
>         """
>         # TODO Check the logic in this function
> ```

Do you need to address this TODO?
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 447 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArQbmBWJV0Iqw3GC5:-NrArQbmBWJV0Iqw3GC6:bnwssq7) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPAnalysisClass.py#L447)):*
> ```Python
>             ) | (self.snp_data_df[self.family_data.reference] != "NoCall")
>         else:
>             # TODO Check the logic in this function
> ```

Do you need to address this TODO?
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 6 [...]

2024-05-06 13:52 UTC, rebeccahaines1 requested changes
In addition to the comments I have added, I agree with RDs comments re docstrings for Classes and Methods. In particular anything that helps show how everything links together. A top level readme would also be useful, or a link to user documentation. 

> Reviewed 42 of 51 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-:-NxD9iT6Ep2ZvpuAgNs_:b7iuskd)* status: all files reviewed, 69 unresolved discussions (waiting on @Graeme-Smith)

___
*[`restart_server.sh` line 8 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NwjAdxdEp81oaRuA2eW:-NwjAdxdEp81oaRuA2eX:b-dk3u7) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/restart_server.sh#L8)):*
> ```Shell
> # Command to restart the server (replace this with the actual command)
> # TODO check the file path for this command on the server
> RESTART_COMMAND="ansible-playbook -i graeme/deployment/inventories/production graeme/deployment/playbooks/basher.yml"
> ```

user specific file path?
Is there documentation anywhere on how to use this?
___
*[`snp_haplotyper/check_inputs.py` line 63 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NwjD4bYAaAqV1sEBcAm:-NwjD4bYAaAqV1sEBcAn:b-pql4wn) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/check_inputs.py#L63)):*
> ```Python
>     ]:
>         logger.error(
>             f"Invalid Mode of Inheritance {input_namespace.mode_of_inheritance} entered as argument, should be 'Autosomal Dominant', 'Autosomal Recessive', or 'X_Linked'"
> ```

is this right? why does X_Linked have an underscore but the others don't. is this error being used to help the user correct the input?
___
*[`snp_haplotyper/check_inputs.py` line 117 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NwjDPHa7i_Mq_NzUWk2:-NwjDPHa7i_Mq_NzUWk3:byv20g1) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/check_inputs.py#L117)):*
> ```Python
>     # Check if flanking_region_size is "2mb" or "3mb"
>     if input_namespace.flanking_region_size.value not in [2, 3]:
>         logger.error("Invalid flanking_region_size: must be either '2mb' or '3mb'.")
> ```

is this to guide the user? if so, might they be confused by this and put "2mb" instead of just 2? Or am I misunderstanding?
___
*[`snp_haplotyper/EmbryoDataClass.py` line 128 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NxD0OLx1R1hxuGXBUeL:-NxD0OLx1R1hxuGXBUeM:bwjgsl5) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L128)):*
> ```Python
>             & ((self.embryo_category_df[self.embryo_id] == "BB"))
>             & consanguineous,
>             (self.embryo_category_df["snp_risk_category_AA"] == "high_risk")
> ```

think there's some duplication here for this and the next 4 items, which are already covered above. Unless I'm missing something?
___
*[`snp_haplotyper/excel_parser.py` line 106 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NwjJOWe7VKKaW4ztWj1:-NwjJOWe7VKKaW4ztWj2:b-91sozb) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/excel_parser.py#L106)):*
> ```Python
> 
>     # Convert float values to text as specified
>     def convert_float_to_text(value):
> ```

why is this function nested?
___
*[`snp_haplotyper/inheritance_logic.py` line 660 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nx8jX6iBN_gWTRyoNlv:-Nx8jX6iBN_gWTRyoNlw:bgi4rox) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L660)):*
> ```Python
>         AB,               BB,                     BB,                   uninformative,        uninformative,        uninformative,        unassigned         # Comment for row 23
>         AB,               BB,                     AB,                   uninformative,        uninformative,        uninformative,        unassigned         # Comment for row 24
>         AB,               AB,                     AA,                   high_risk,            low_risk,             high_risk,            unassigned         # Comment for row 25
> ```

couldn't find this in the logic diagram or written out in the text for a AB female reference so couldn't check https://docs.google.com/document/d/1QKdQ-XpD8TFaxhdP41X8-BrUc0j9gENGrIBnYhPtJiE/edit
Its also missing in https://github.com/moka-guys/SNP_haplotyper/blob/git_version_in_report/docs/source/SNPHaplotyperXLinkedLogic.html- please clarify which is correct. If the html file is correct, then this part of the code is wrong.
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 51 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nx8lKDb5yzP2Bg3ykhe:-Nx8lKDb5yzP2Bg3ykhf:b-2vi30t) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPAnalysisClass.py#L51)):*
> ```Python
> mod_path = Path(__file__).parent
> 
> import config as config
> ```

already done this above?
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 138 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nx8mSOG1YhJwGvWiC6z:-Nx8mSOH9zUegZkYvhWQ:b8eunjg) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPAnalysisClass.py#L138)):*
> ```Python
>         classes: str = "table table-striped",
>     ) -> str:
>         # This method currently just returns the table_name for demonstration purposes.
> ```

are these comments still relevant?
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 149 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nx8n2xsCvGTQJOBvAQ8:-Nx8n2xsCvGTQJOBvAQ9:bx6hovh) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPAnalysisClass.py#L149)):*
> ```Python
> 
> 
> class AutosomalDominantFormatter(EmbryoTableFormatter):
> ```

as elsewhere, class and method docstrings would be very helpful here
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 448 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nx8vi7jEI5nRnh32Uxt:-Nx8vi7jEI5nRnh32Uxu:b-7h7965) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPAnalysisClass.py#L448)):*
> ```Python
>         else:
>             # TODO Check the logic in this function
>             # For autosomal and recessive cases all NoCalls should be filtered out
> ```

is this comment link correct, i.e. "autosomal and recessive"- should this be "autosomal dominant and recessive"
___
*[`snp_haplotyper/SNPDataClass.py` line 45 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NxD6qnW3sNnaQo4i3gU:-NxD6qnW3sNnaQo4i3gV:bhgv3l) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPDataClass.py#L45)):*
> ```Python
> from dataclasses import dataclass
> 
> import config as config
> ```

already imported above?
___
*[`snp_haplotyper/snp_haplotype.py` line 31 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NxCl_rS8BvJo-b8vRlg:-NxCl_rS8BvJo-b8vRlh:bg43m6w) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/snp_haplotype.py#L31)):*
> ```Python
> from pydantic.dataclasses import dataclass
> 
> # Import mode of inheritance specific code
> ```

is this comment still relevant?
___
*[`snp_haplotyper/snp_haplotype.py` line 39 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NxClTEXAzHrXeSV8wk9:-NxClTEXAzHrXeSV8wkA:byurtne) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/snp_h [...]

2024-05-08 14:24 UTC, Graeme-Smith reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-:-NxHRB74-j2V0tjekVZ6:bnfp4nl)* status: all files reviewed, 69 unresolved discussions (waiting on @RachelDuffin and @rebeccahaines1)

___
*[`Makefile` line 20 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0T7ZrAa0VOokywLaA:-NxNMwJG17UdoS47Ayao:bgffjws) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/Makefile#L20)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Suggestion to add a docker save command to the Makefile to standardise the saving of the image to a zip file. e.g.: https://github.com/moka-guys/duty_csv/blob/main/Makefile
</blockquote></details>

I have added Docker Save command
___
*[`restart_server.sh` line 8 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NwjAdxdEp81oaRuA2eW:-NxNOPFmC1vv1Cs1SEQO:b-653xdd) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/restart_server.sh#L8)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

user specific file path?
Is there documentation anywhere on how to use this?
</blockquote></details>

I've added this to the deployment documentation.
___
*[`docs/source/development.md` line 136 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0jGdW6pjvHliG8roR:-NxNZeBq0ACmUxYOd79I:ba3dfob) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/docs/source/development.md#L136)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Should this TODO be here?
</blockquote></details>

Removed
___
*[`snp_haplotyper/app.py` line 69 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0jgoLAuGW32KEyTSg:-NxNZxieB0kUl14x1dYz:b-6cuvdj) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/app.py#L69)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Incomplete comment
</blockquote></details>

I've added the end to the comment.
___
*[`snp_haplotyper/check_inputs.py` line 63 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NwjD4bYAaAqV1sEBcAm:-NxHOXZq6O0SjAs5JwM7:bfvljgz) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/check_inputs.py#L63)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

is this right? why does X_Linked have an underscore but the others don't. is this error being used to help the user correct the input?
</blockquote></details>

Corrected to X-linked
___
*[`snp_haplotyper/EmbryoDataClass.py` line 23 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6Cd2r0ivLeYxdcWwN:-NxK9_6R6EPLMDfUY5V3:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L23)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Please can you add a class docstring. E.g. https://github.com/moka-guys/automate_demultiplex/blob/833445d3773e5408905410eb8331ab4f0c3ef64a/demultiplex/demultiplex.py#L34-L67

It  makes it a lot easier for someone picking up the code to understand what the class attributes and methods are / their types
</blockquote></details>

Done.
___
*[`snp_haplotyper/EmbryoDataClass.py` line 47 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6Cke883c384KufyKV:-NxNFQA-3HHQKRnW43MZ:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L47)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Please can you add a docstring
</blockquote></details>

Done.
___
*[`snp_haplotyper/EmbryoDataClass.py` line 51 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6CgZ64pjm3wLrVnUc:-NxK9bJR408a0KLGLdWK:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L51)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Please can you add a class docstring
</blockquote></details>

Done.
___
*[`snp_haplotyper/EmbryoDataClass.py` line 88 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6Du6J4urC11512CxX:-NxNFTZN913QxV82eq7V:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L88)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Please can you add a class docstring
</blockquote></details>

Done.
___
*[`snp_haplotyper/EmbryoDataClass.py` line 182 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6CxFs0nn_yEjO0sr9:-NxK9d-S87-mLYdhttKL:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L182)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Please can you add a class docstring
</blockquote></details>

Done.
___
*[`snp_haplotyper/EmbryoDataClass.py` line 693 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6E0yy9uBQZw28rl9F:-NxNFXHO0r-HdaSUTmdE:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L693)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Please can you add a class docstring
</blockquote></details>

Done.
___
*[`snp_haplotyper/EnumDataClasses.py` line 31 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6HFR47zv_BQ3UWtTh:-NxNFb8V4O72DVHM70Y3:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EnumDataClasses.py#L31)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Add 2 spaces between classes
</blockquote></details>

Done.
___
*[`snp_haplotyper/FamilyDataClass.py` line 19 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6N67pCP8gCbqfjpAG:-NxK9gAf10Fy9d7ZeFmx:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/FamilyDataClass.py#L19)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Docstring
</blockquote></details>

Done.
___
*[`snp_haplotyper/inheritance_logic.py` line 10 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6N_dC38OTKVro6uA-:-NxNFltsAxjvaMzR_qGE:b-896fix) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L10)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Documentation
</blockquote></details>

Done.
___
*[`snp_haplotyper/inheritance_logic.py` line 35 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArrLjCVHJfh_vWr1F:-NxIljmo0vNRRvBPLuXX:b-5a4cm3) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L35)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Would data like this be better stored in a separate csv file and read in?
</blockquote></details>

I kept this with the code which utilised it to increase the cohesion of the code and to help with debugging/validation
___
*[`snp_haplotyper/inheritance_logic.py` line 332 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArzV1-oGqdXQmeYs-:-NxIm3e0C16cIgoUnzD-:b-5a4cm3) ([raw file](https://gith [...]

2024-05-09 23:05 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9)* status: all files reviewed, 69 unresolved discussions (waiting on @RachelDuffin and @rebeccahaines1)

___
*[`snp_haplotyper/EnumDataClasses.py` line 55 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6HJop7LZBqUkkebzL:-NxUaC_QD1r9NiGVxpHz:bvdgxy0) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EnumDataClasses.py#L55)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Do you need to address the #TODO
</blockquote></details>

Removed in refactor
___
*[`snp_haplotyper/excel_parser.py` line 106 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NwjJOWe7VKKaW4ztWj1:-NxNamTvEj7oy3alCNMh:b7oeo30) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/excel_parser.py#L106)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

why is this function nested?
</blockquote></details>

It gives the function local scope to the load\_workbook\_range() function.  The convert_flaot_to_text function isn't used outside this function and it keeps the code cohesive.
___
*[`snp_haplotyper/FamilyDataClass.py` line 135 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6NANZ9oHm5EpoW56Y:-NxUaGn4-QIe12mQw0EV:bvdgxy0) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/FamilyDataClass.py#L135)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

There is a TODO and commented out lines
</blockquote></details>

Removed in refactor
___
*[`snp_haplotyper/ReportDataClass.py` line 59 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArG-c7QxGWCo2N6AE:-NxUaIKq0qsx76imV2nK:bvdgxy0) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/ReportDataClass.py#L59)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Do you need to address these TODOs?
</blockquote></details>

Removed in refactor
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 13 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArJ9x8vVjhETnuWRj:-NxUaKD3DbsPDs_jSGYD:bvdgxy0) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPAnalysisClass.py#L13)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Do you need to address this TODO?
</blockquote></details>

Removed in refactor
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 51 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nx8lKDb5yzP2Bg3ykhe:-NxT6FZiDT6zb3OirYWg:b-fdohtm) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPAnalysisClass.py#L51)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

already done this above?
</blockquote></details>

Removed duplicate
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 440 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArMZS2B0IBnkAm1al:-NxUaMUqBXAkA0EKh5lG:bvdgxy0) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPAnalysisClass.py#L440)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Do you need to address this TODO?
</blockquote></details>

Removed in refactor
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 622 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArS4LE9OKqoIbvw6f:-NxUaPT8Ehvipeh8wnpH:bvdgxy0) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPAnalysisClass.py#L622)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Do you need to address this TODO?
</blockquote></details>

Removed in refactor
___
*[`snp_haplotyper/SNPDataClass.py` line 188 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrB5yP4DPmtBNg1PBq_:-NxUaRyb7ojXYBlH_kdk:bvdgxy0) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPDataClass.py#L188)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Does this TODO need addressing?
</blockquote></details>

Removed in refactor
___
*[`snp_haplotyper/SNPDataClass.py` line 724 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrB6NfI8kiX8od9atzh:-NxUaTLP7AT66f2woJv4:bvdgxy0) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPDataClass.py#L724)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

DOes this todo need addressing?
</blockquote></details>

Removed in refactor
___
*[`snp_haplotyper/snp_haplotype.py` line 13 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArTMOAFfj9YlUOgtp:-NxUaWd-5ebS0ZvUULJy:bvdgxy0) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/snp_haplotype.py#L13)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Do you need to address this TODO?
</blockquote></details>

Removed in refactor
___
*[`snp_haplotyper/snp_haplotype.py` line 39 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NxClTEXAzHrXeSV8wk9:-NxT8Xm83RdwY1lD65KD:bkfp1c4) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/snp_haplotype.py#L39)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

hasn't this been imported already above?
</blockquote></details>

Removed duplicate
___
*[`snp_haplotyper/snp_haplotype.py` line 53 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArUgfEQwhjG53yq_i:-NxUaYOxA-M4EhHrjIH3:bvdgxy0) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/snp_haplotype.py#L53)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Do you need to address these TODOs?
</blockquote></details>

Removed in refactor
___
*[`snp_haplotyper/snp_haplotype.py` line 166 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NxCnisb1xkbFnv5Ti--:-NxT8giuE98apnj1W7pi:b-1dcph8) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/snp_haplotype.py#L166)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

female partner?
</blockquote></details>

Corrected
___
*[`snp_haplotyper/snp_haplotype.py` line 174 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NxCno3t0SO8THGI868P:-NxU_dYa9fn-1xxMjyEz:b-1dcph8) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/snp_haplotype.py#L174)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

status of female partner?
</blockquote></details>

Corrected
___
*[`snp_haplotyper/snp_haplotype.py` line 365 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArcAQ6DDO_wEWHG6a:-NxUa1bW7dqP3oVecDef:bvdgxy0) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/snp_haplotype.py#L365)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Do you need to address this TODO?
</blockquote></details>

Removed in refactor
___
*[`snp_haplotyper/validate_output.py` line 194 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArf5M4MAYZ3hD4M4L:-NxUac9N-1OwRanVUjCZ:bvdgxy0) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec6 [...]

2024-05-11 17:33 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9)* status: all files reviewed, 69 unresolved discussions (waiting on @RachelDuffin and @rebeccahaines1)

___
*[`snp_haplotyper/check_inputs.py` line 117 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NwjDPHa7i_Mq_NzUWk2:-NxUbO6_3mn2u_eKCHnV:b-p8rtvl) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/check_inputs.py#L117)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

is this to guide the user? if so, might they be confused by this and put "2mb" instead of just 2? Or am I misunderstanding?
</blockquote></details>

Rewritten
___
*[`snp_haplotyper/check_inputs.py` line 138 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0k0rcE3irn_tv0G34:-NxbsPTC69NT0b4Gpmc_:b-ggo51q) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/check_inputs.py#L138)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Should these lines of code be commented out? Or removed?
</blockquote></details>

Removed as these values are now enums and cannot be an empty string
___
*[`snp_haplotyper/check_inputs.py` line 228 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0k8HI1LPrsMnpbE_t:-NxbsZsm8U-fbpXt-fKp:b-ggo51q) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/check_inputs.py#L228)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Should these lines be commented out? Or emoved
</blockquote></details>

Removed as these values are now enums and cannot be an empty string
___
*[`snp_haplotyper/classes_snp_haplotyper.png` line  at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0qNjVA5x4Qe2b14Ah:-Nxcb_dx7a92zXaW_2Xz:b-i6e29b) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/classes_snp_haplotyper.png#L)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

I have had a quick look at this class diagram and it seems like it does not map all the relationships between classes?

e.g. https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPDataClass.py#L512C31-L524C1

But there is no relationship mapped between InheritanceLogicFactory and AutosomalDominantLogic
</blockquote></details>

I've regenerated the images
___
*[`snp_haplotyper/EmbryoDataClass.py` line 128 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NxD0OLx1R1hxuGXBUeL:-NxUgSyQ2_KNrTOaKCCR:byge8ld) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L128)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

think there's some duplication here for this and the next 4 items, which are already covered above. Unless I'm missing something?
</blockquote></details>

Removed duplication
___
*[`snp_haplotyper/EmbryoDataClass.py` line 779 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6F-jhAMuOHZS6qJhh:-NxbxXJg3E3qvEKKZkrw:b1jrbut) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L779)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Why do you need a function that returns a class attribute? You should be able to just access it from the class directly e.g. 

embryo_data = EmbryoData()
embryo_data.embryo_category_df
</blockquote></details>

Three main reasons why I don't like to access from the class directly:

-   **Encapsulation**: The approach is part of an effort to encapsulate the behavior or state of the class, preventing external code from depending directly on the class's internal representation. This can be useful for maintaining flexibility to change the attribute's internal implementation without affecting its consumers.

-   **Consistency**: If other properties or attributes are accessed via methods or properties due to complexity, using a method for simpler attributes as well can keep the class interface consistent.

-   **Future-proofing**: The function might be used in a future scenario where accessing the attribute might need additional logic or operations, , like validation or transformation of the data before returning it.
___
*[`snp_haplotyper/EmbryoDataClass.py` line 782 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6FHTz54Z7Y1ORqbEJ:-NxbyBn2-YKPHg99jR8T:b-33b6k6) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/EmbryoDataClass.py#L782)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

See comment above
___
*[`snp_haplotyper/excel_parser.py` line 266 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6IYJp1C2WLdcN4ke7:-Nxcgozp6zD3KyisI9Ik:bb7o13c) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/excel_parser.py#L266)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Can this be done when the variable is first declared?
</blockquote></details>

You can specify something like:

embryo\_data\_df = pd.DataFrame(data).astype(str)

However thats when you are defining the data explicitly, I am using the function argument_dict() to read it into the dataframe and I prefer to keep this function generalised i.e. I can use it for use cases where perhaps I do not want all the columns to be strings.
___
*[`snp_haplotyper/inheritance_logic.py` line 108 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrAqCCvDdUez6OTNYae:-NxbyJsY2jNaTYwootUy:b-33b6k6) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L108)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Same as above - is this needed when it can be accessed from the object directly
</blockquote></details>

See comment above
___
*[`snp_haplotyper/inheritance_logic.py` line 261 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrAqjpTDqcBcTLqauSq:-NxUh5-P9r5idGqsUB53:b-q90fa5) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L261)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Do you need to reassign these? pretty sure you should be able to access them by self.carrier_female_partner for example - I may be wrong though
</blockquote></details>

It allows generic code to  be used across all modes of inheritance while retaining the termonology used in the PGT-M team
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 138 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nx8mSOG1YhJwGvWiC6z:-NxUhTjk6J6a8ujFXixC:be48xyw) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPAnalysisClass.py#L138)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

are these comments still relevant?
</blockquote></details>

Comment has been removed
___
*[`snp_haplotyper/SNPAnalysisClass.py` line 447 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-NrArQbmBWJV0Iqw3GC5:-NxUhXmc3iZPJY-ja91-:b-gz7v1x) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/SNPAnalysisClass.py#L447)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Do you need to address this TODO?
</blockquote></details>

TODO removed
___ [...]

2024-05-14 08:54 UTC, Graeme-Smith reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9)* status: all files reviewed, 69 unresolved discussions (waiting on @RachelDuffin and @rebeccahaines1)

___
*[`snp_haplotyper/check_inputs.py` line 271 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr0kBDi5w6pt_RAGG46:-NxqI9Ju69rltvxrV_7J:bpoaxru) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/check_inputs.py#L271)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Should these lines be commented out? or removed?
</blockquote></details>

I've uncommented these
___
*[`snp_haplotyper/excel_parser.py` line 395 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nr6LA1LC1qdUmBjBOio:-NxqIHN92i7Wur7DHDX7:brk0ppb) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/excel_parser.py#L395)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Why is the above commented out?
</blockquote></details>

I've removed this comment
___
*[`snp_haplotyper/inheritance_logic.py` line 660 at r2](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9#-Nx8jX6iBN_gWTRyoNlv:-NxqIhEQAErOOorIk444:b-77yf65) ([raw file](https://github.com/moka-guys/SNP_haplotyper/blob/4f3cec624089ff3d5e89bd02bb09a12ff8fa6abc/snp_haplotyper/inheritance_logic.py#L660)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

couldn't find this in the logic diagram or written out in the text for a AB female reference so couldn't check https://docs.google.com/document/d/1QKdQ-XpD8TFaxhdP41X8-BrUc0j9gENGrIBnYhPtJiE/edit
Its also missing in https://github.com/moka-guys/SNP_haplotyper/blob/git_version_in_report/docs/source/SNPHaplotyperXLinkedLogic.html- please clarify which is correct. If the html file is correct, then this part of the code is wrong.
</blockquote></details>

I will update the source document with the correct logic


<!-- Sent from Reviewable.io -->

2024-05-14 15:10 UTC, rebeccahaines1 approved these changes
> Reviewed 51 of 51 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9)* status: all files reviewed, 54 unresolved discussions (waiting on @RachelDuffin)



<!-- Sent from Reviewable.io -->

2024-05-14 15:37 UTC, RachelDuffin approved these changes

2024-05-14 15:39 UTC, RachelDuffin approved these changes
> Reviewed 51 of 51 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/SNP_haplotyper/9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Graeme-Smith)



<!-- Sent from Reviewable.io -->

2024-05-14 15:39 UTC, merged